### ISSUE TITLE
feature request encrypted store

### ISSUE THREAD

**Issue by Pomax** [louischatriot/nedb#114]
I was playing with nedb for my flickrmirror software (which doesn't really need a huge store so from-file with incidental polls is perfectly fine) but was thinking of making the datastore file itself encrypted using a simple crypted stream, but it might be nice to bake that into nedb itself, so that you can do something like

```
var db = new Datastore({
  filename: "./data/users.datastore",
  autoload: true,
  key: env.get("user_store_key") // optional, if used, uses encrypted file store
});
```

and have it use an encrypted stream to read and write to the store files, just to make it a little harder to do anything with the store file if it somehow makes it off the server. Would this be worth doing?

**Comment by louischatriot** [comment]
I created some failsafe mechanisms, thought they were necessary, see readme
