### ISSUE TITLE
find() and filtering date fields

### ISSUE THREAD

**Issue by b1rdex** [louischatriot/nedb#139]
Assume we have date field in docs. How can I filter result set for date > 01.02.2014 and date < 25.02.2014?

Tryed `table.find({ date: { $gte: moment().startOf("month").toDate() }` and `table.find({ date: { $gte: moment().startOf("month").toDate().getTime() }` -- they're not working.

**Comment by mithun-daa** [comment]
@subutux Will your solution work for the timestamps created by NeDB? I cannot seem to be able to get anything back if I use `createdAt`

```
db.find({createdAt : { $gte: moment().startOf("month").toDate().toJSON() }},function(err,docs){console.log(err,docs);});
```
