### ISSUE TITLE
Datasets up to 1GB?

### ISSUE THREAD

**Issue by szwacz** [louischatriot/nedb#14]
Hello Louis.
NeDB looks really awsome at first glance. Little brother of MongoDB is just what I was looking for to use with node-webkit.
In my application single database could easily grow to 1GB. Will be NeDB capable of handling such large files in nearest future? Handling whole database in memory ofcourse is not an option :)

regards
Jakub

**Comment by hungpn2212** [comment]
Can NeDB handle large databases now? I'm a student and i'm working on an assignment for my DBMS class.

The topic is compare the performance of a traditional relational database to a new NoSQL database (Such as NeDB). Each of the databases must contain at least 100m records.

**Comment by prust** [comment]
@hungpn2212: From the readme:

> NeDB is not intended to be a replacement of large-scale databases such as MongoDB, and as such was not designed for speed. That said, it is still pretty fast on the expected datasets, especially if you use indexing. On a typical, not-so-fast dev machine, for a collection containing 10,000 documents

NeDB's performance, especially at scale, is not representative of typical NoSQL databases. I would strongly encourage you to use a more typical NoSQL database to get a more useful comparison. MongoDB is one of the most popular in the node community (Cassandra or Riak would be interesting points of comparison as well, though their performance characteristics may be quite different, I don't know off the top of my head)
