### ISSUE TITLE
Unicode support for .sort and .find

### ISSUE THREAD

**Issue by alsciende** [louischatriot/nedb#150]
It doesn't look like NeDB supports unicode sorting. I opened an issue in taffydb (https://github.com/typicaljoe/taffydb/issues/66) to explain the problem, but didn't get any feedback, though I submitted a pull request. I'll switch to NeDB if it supports different collations for databases.

That could be done on a global level for the database (specifying the locale at the creation of the database), or at a local level (specifying the locale for an operation).

Test case:

```
var db = new Nedb();
db.insert([{name:"a"},{name:"â"},{name:"Â"},{name:"A"},{name:"Z"},{name:"z"}]);
db.find({}).sort({ name: 1 }).exec(function (err, records) {
  console.log(records.map(function (record) { return record.name }));
}); 
// outputs ["A", "Z", "a", "z", "Â", "â"] 
// (apparently we cannot opt for case-insensitive sort)
// correct i18n output would be something like :
// ["a", "â", "Â", "A", "Z", "z"]
// (assuming generic utf-8 and case-insensitive sort)
```

That result could be achieved by using `Intl.Collator` which does have a `compare` method.

**Comment by wedihaddish** [comment]
i guess i have a the same issue with the unicode my json is geez unicode here is what it looks like 
_______________________________________________________________________________
{"entry":"cockeyed","supportinfo":"","pronuncation":"’ኮክ’ኣይድ","partofspeech":"ቅጽል","definition":"1. ሸውራር፤ ሓውላል።\n\n2. ቄናን፤ ዘምባል።\n\n3. ሓውሲ ጽሉል ዝኾነ፤ ሕንፍሽፍሽ፤ ፋሕፋሕ ዝበለ (ንኣ. ንመደብ)፤\n\n4. ዝሸገገ፤ ዝሰኸረ፤ ስኹር።","_id":"ym8Qk5fo6iZiaPRL"}
{"entry":"cine-camera","supportinfo":"","pronuncation":"’ሲኒ ካ፤ም፡ረ","partofspeech":"ስም","definition":"ሲነ-ካሜራ (መስኣሊት ሲነማ)።","_id":"ymOUPGExeoKZv37K"}
{"entry":"disunion","supportinfo":"","pronuncation":"ዲስ’ዩ፡ንይ፡ን፤ዲሽ ’ዩ፡ንይ፡ን","partofspeech":"ስም","definition":"ምፍራስ ናይ ሕብረት ወይ ሓድነት፤ ምብትታን፤ ምፍልላይ፤ ምግዝዛዕ፤ ምክፍፋል።","_id":"ymt9OM2dRMrEZKfD"}
{"entry":"paterfamilias","supportinfo":"","pronuncation":",ፐይት፡ፍ፡ሚሊያ፤ስ/ፓ፤ት፡-","partofspeech":"ስም","definition":"ኣቦ ስድራ፤ ኣቦ ገዛ።","_id":"ymtVltuLEhjVr1Aj"}
__________________________________________________________________________
when i try to use find the geez unicode is returned like square it is not readable 
the code is like this 
/*
		Author:biniam Haddish;
		Date:11-10-2015;
		App_name:English Tigrigna Dictionary;
		Technology:nedb db,node webkit,material design,HTML5,Angularjs;
 */
/*-------------------------------------------------------------------------*/
var dataFileUrl='db/Etig.json';
var dicItems  = [];
var Datastore = require('nedb'),wordCollection = new Datastore({ filename: dataFileUrl,autoload: true });

  /*--------------------------------------------------------------------*/
 function getAllIteams(word){
   $('#suggestions').html('');
  	wordCollection.find({entry:word},{ entry:1,supportinfo:1,definition:1,_id:0},function(err,allWords){
  		    //console.log("from nedb "+'\n', JSON.parse(JSON.stringify(allWords[0]).replace("'", "\"")).definition);
  	     var stringf = JSON.parse(JSON.stringify(allWords[0]).replace("'", "\"")).definition;
         $('#suggestions').append(stringf.toString())+'</br>';
 
  	});
  }

how do i deal with this??
______________________________________________________________________________
