### ISSUE TITLE
Delay write to disk

### ISSUE THREAD

**Issue by PSeitz** [louischatriot/nedb#189]
Would be nice to be able to set a delay oder an interval before changes are written to disk, since this has a massive impact on performance.

**Comment by PSeitz** [comment]
After thinking about it one year .. ;)
I think something like BEGIN TRANSACTION and COMMIT would be nice. This way you have control about what is written to disk plus the performance boost.

**Comment by louischatriot** [comment]
Unfortunately this will most likely not be done. Work on NeDB is pretty much finished as of today, with all the main objectives being met. I could consider it though if you can explain convincingly why you need such performance from NeDB, as I think it is already more than fast enough for its intended usecases.

**Comment by louischatriot** [comment]
Actually the writing to disk was handled by the OS and not done before returning from writeFile and append calls, so this would not bring a real performance boost. NeDB always lets the OS handle writes to disk except when compacting the file to ensure the database cannot be lost, see persistence chapter of the readme.
