### ISSUE TITLE
Proposal: document serialization/deserialization hooks

### ISSUE THREAD

**Issue by szwacz** [louischatriot/nedb#195]
We've been talking about ways to allow people to store natively more rich data types (like buffers). I thought about the problem a little, but the solution I came up with is not astonishingly pretty, so I want to show it before implementation to get general agreement that this is the best way.

Everybody feel free to say what you think about this. If noone has any complaints I will implement it and submit as a PR.

Code below implements storage encryption and Buffer as natively-supported type.

``` js
var transformForSerialization = function (obj) {
    Object.keys(obj).forEach(function (key) {
        var val = obj[key];
        if (Buffer.isBuffer(val)) {
            // Using __ as prefix, because $$ is reserved for NEDB internal use only.
            obj[key] = { __buffer: val.toString('base64') };
        } else if (typeof val === 'object' && !Array.isArray(val) && val !== null) {
            transformForSerialization(val);
        }
    });
};

new Datastore({

    // You can pass to constructor two functions throug which the serialization 
    // process will be streamed, so you can alter its behaviour.

    // doc - the document about to be serialized for storage
    // coreSerialize - core (internal) NEDB serialize function exposed for usage
    serialize: function (doc, coreSerialize) {
        // Custom transformations on document object
        transformForSerialization(doc);

        // Next step is to call core serialization, which does 
        // the real job of turning object into JSON.
        var rawData = coreSerialize(doc);

        // Thanks to access to rawData we can then encrypt it if we need to.
        var encrypted = encrypt(rawData);

        // NEDB checks if value returned by this function is a string and doesn't 
        // contain any linebreaks, otherwise throws exception.
        return encrypted;
    },


    deserialize: function (rawData, coreDeserialize) {
        // Analogous to serialize, but inverted order.
    }

});
```

**Comment by louischatriot** [comment]
I created some failsafe mechanisms, thought they were necessary, see readme

**Comment by david-rodrigue** [comment]
This works great, thanks!

**Comment by ShwetaDua** [comment]
Hi,

I tried encryption and decryption using nedb using below code. But the db is overwritten everytime i run this file. Also, find query does not return any result. Can you please suggest.

var Datastore = require('nedb');
var crypto = require('crypto');
var assert = require('assert');

var algorithm = 'aes256'; // or any other algorithm supported by OpenSSL
var key = 'password';
var db = new Datastore({ filename: 'path/to/shweta01212',
 autoload: true,
    afterSerialization: function (doc) {

var encrypted =doc;
        /*if(/^[\],:{}\s]*$/.test(doc.replace(/\\["\\\/bfnrtu]/g, '@').
         replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g, ']').
         replace(/(?:^|:|,)(?:\s*\[)+/g, '')) ){
         console.log(doc);
         }*/
        try{
			var ef;
            if(JSON.parse(doc) && isNaN(doc)){

var cipher = crypto.createCipher(algorithm, key);
 encrypted=cipher.update(JSON.stringify(doc), 'utf8', 'hex') + cipher.final('hex');
  ef = encrypted;
console.log("Ser" +encrypted);
return encrypted;
            }
        }catch(e){

        }
da=encrypted;


    },


    beforeDeserialization: function (doc) {
//console.log(doc);
        if (doc != undefined && doc != "") {

            var decipher = crypto.createDecipher(algorithm, key);

            var decrypted = decipher.update(doc, 'hex', 'utf8') + decipher.final('utf8');
             console.log("decipher" + decrypted);
            return decrypted;
        }
        //console.log("decipher2	" + da);
        return da;
    }

});
/*db.loadDatabase(function (err) {    // Callback is optional

});*/
/*db.insert({ a: "Hello23", _id: 'id123' }, function (err, newDocs) {
   console.log("in"+err);
});

db.insert({ a: "Hello22", _id: 'id12' }, function (err, newDocs) {
   console.log("in"+err);
});*/

db.find({ a: "Hello22", _id: 'id12' }, function (err, doc) {
console.log(doc);
});
