### ISSUE TITLE
more than 2GB memory

### ISSUE THREAD

**Issue by wenbob** [louischatriot/nedb#206]
I need a large in-memory cache , when I insert more items, process out of memory .
then I found this limit:
https://github.com/v8/v8/blob/c8bf5c35e431d4029e084024501863a4cf907882/src/objects.h#L4647-L4648

new Buffer() can break this limit, so...JSON object should be convert into Buffer object?

**Comment by maheshsetti** [comment]
Is new Buffer() really good solution?

**Comment by louischatriot** [comment]
Nope buffer are limited. In any case the V8 memory is limited to 1.7 GB.

**Comment by tracker1** [comment]
@wenbob depending on your use case, you may want to consider using Redis for this... the added benefit is that you can access a redis store from multiple processes, so if needed more than one instance/fork/cluster of your application can access the same data.

**Comment by maheshsetti** [comment]
Thanks @wenbob are you sure if we go  with redis for my node-webkit desktop app can i overcome the storage limitation?
