### ISSUE TITLE
Add bower.json

### ISSUE THREAD

**Issue by cjroth** [louischatriot/nedb#211]
Since nedb can be loaded in the browser, why not add it to bower?

**Comment by andyhu** [comment]
+1

**Comment by andyhu** [comment]
+1

**Comment by gossel-j** [comment]
It is an old issue, nedb is really great and miss a bower.json a lot.

**Comment by louischatriot** [comment]
There is now a bower.json. nedb can be installed, as was the case before, by `bower install nedb` but it doesn't show up in the bower search results. This seems to be an issue with bower which I don't think is worth investigating.
