### ISSUE TITLE
Upserting keeps adding duplicates of the same record to the database

### ISSUE THREAD

**Issue by giacecco** [louischatriot/nedb#226]
See the code below, upserting the same record three times in a row:

```
var Nedb = require('nedb');
var db = new Nedb({ filename: 'test.db' });
db.loadDatabase(function (err) { 
    db.update({ '_id': 'foo_id' }, { somedata: 'hello' }, { 'upsert': true }, function (err, numReplaced) {
        console.log(numReplaced, err);
        db.update({ '_id': 'foo_id' }, { somedata: 'hello' }, { 'upsert': true }, function (err, numReplaced) {
            console.log(numReplaced, err);
            db.update({ '_id': 'foo_id' }, { somedata: 'hello' }, { 'upsert': true }, function (err, numReplaced) {
                console.log(numReplaced, err);

            });
        });
    });
});
```

At the end of execution, _test.db_ is:

```
{"somedata":"hello","_id":"foo_id"}
{"somedata":"hello","_id":"foo_id"}
{"somedata":"hello","_id":"foo_id"}
```

I'm on Mac OS Yosemite (10.10.1) running nodejs 0.10.33 and nedb 0.11.1. This issue goes well with the other one I found some time ago https://github.com/louischatriot/nedb/issues/217 . Thanks!

Giacecco

**Comment by smartytwiti** [comment]
@louischatriot I come accross to this problem also, it would be better to make a notice in a subsection of update/delete section.  no one reads the whole readme fro a simple update documentation. Thanks!

**Comment by martinsookael** [comment]
So anyone ending up here with a google search (and finding the link to #compacting-the-database not working), the answer from README is:   
   
> Under the hood, NeDB's persistence uses an append-only format, meaning that all updates and deletes actually result in lines added at the end of the datafile, for performance reasons. 

So the following ought to be normal behaviour (although looks terrifiyng):
```
{"username":"admin","password":"xxx","_id":"0GWpCrKe1C6Pp49i"}
{"username":"admin","password":"xxx","_id":"0GWpCrKe1C6Pp49i","token":"xxxx.xxxxx.xxxxx"}
{"username":"admin","password":"xxx","_id":"0GWpCrKe1C6Pp49i"}
```
Although the token is actually removed from the db and not searchable, it's stil visible in the db file.

**Comment by lukasbestle** [comment]
If you compact the database or reload it the next time you start the application, the old entries are physically deleted from the file automatically. You can manually compact if you don't want to keep the token in the database file.

**Comment by murindwaz** [comment]
This behaviour(feature) is confusing. 
If you ever have another free time, add a segment to prevent users from using it the wrong way.
I come from MongoDB word, and reason I adopted nedb is its similarity with MongoDB.

db.somecollection.insert({xx: yy})
db.somecollection.insert({xx: zz})

inserts two records, and db.somecollection.find({}) returns two records,
but I realized it returns only first record at very end of the project.

Good Job, keep it up.

**Comment by bdfoster** [comment]
It's a feature in the sense that it increases performance. Normally, you
don't access MongoDB's raw files in order to make sense of the database,
you use their API. You can do the same, if you wish, but obviously it's
easier to pop open the file and take a look. Don't fault NeDB on how it
stores data unless it's actually at fault. That file is meant for the
computer, not you.

**Comment by ivanjzr** [comment]
Whenever I upsert and do not have records the user_upsert is undefined do you know why?
  // Upserting a document
    users.update({ id: user_data.id }, user_data, { upsert: true }, function (err, numReplaced, user_upsert, affected) {
      console.log(numReplaced, user_upsert, affected);
     // this will be 1, undefined, undefined even when there is the document
    });

    users.persistence.compactDatafile();
