### ISSUE TITLE
Memory can provide fine-grained control

### ISSUE THREAD

**Issue by zg2013** [louischatriot/nedb#237]
google translation, we non-English speaking countries  :)

My team fell in love with NEDB!
We tried to use these databases：
  sqlite
  EJDB
  Firebird
  H2
  HTML5 indexedDB
  Leveldb
  LowDB
  PouchDB
  StoreDB
  and NeDB！

We feel NEDB best for us.
it's very flexible and very fast.

We hope you will stick with it
We really need him.

But there are disadvantages that consume too much memory. We use this database on the client, our software memory footprint is 40M, but our ultimate stress test data, our software footprint is 110.
I hope you can provide a method for controlling a memory so that we adjust memory usage, because not all of the data takes a long time to load in memory.

Thank you for your work!

**Comment by louischatriot** [comment]
As of v1.4, NeDB automatically selects the best method to persist data on the browser (IndexDB then WebSQL then localStorage), so the limit is removed. WARNING: it's not back compatible with v1.3, but that should not be a major issue as user apps can resync entirely.
