### ISSUE TITLE
Model serialization broken in browser-version on Safari

### ISSUE THREAD

**Issue by tathata** [louischatriot/nedb#248]
I've added some tests for the browser version (https://github.com/louischatriot/nedb/pull/247) which target the use of localStorage.  I came across an issue in Safari that I believe is related to the serialization/deserialization process.  By modifying those functions in model.js so that we don't pass a callback as the second parameter to JSON.stringify and JSON.parse, the tests pass.

**Comment by louischatriot** [comment]
As mentioned in #247 I couldn't reproduce, so I closed the issues.
