### ISSUE TITLE
nedb goes slow after the app runs a long time.

### ISSUE THREAD

**Issue by asinverse** [louischatriot/nedb#249]
Hi all,

I'm using nedb in my node-webkit app and I have a problem with "find" function on OSX.
At the beginning, the nedb works perfectly, it's very fast. 
After an hour, just keep the app running, I make a same request as beginning and nedb takes 2s to return the result.
Then, after 3, 4 hours, still same request, and it takes 4s and more to return the result.

Does anyone have same problem as me? Can someone give me a suggestion for this problem?
Thank you,

**Comment by prust** [comment]
@asinverse: Is your app storing lots of additional data in NeDB over the 3-4 hours? NeDB stores all its data in an internal data structure (I think it's an object) -- all the operations on this object will be slower if it has a ton of keys/data stored on it.

**Comment by asinverse** [comment]
Thank you @prust. I've tested with a database that has 2000 rows and 3 columns indexed. During testing, I just make "find" query, no "insert", "update" or "remove".

**Comment by prust** [comment]
@asinverse: Hm, sounds like a memory leak. Perhaps related to https://github.com/louischatriot/nedb/issues/209?

**Comment by prust** [comment]
@asinverse: I did a quick survey of the `find()` code and the cursor code that it calls, but didn't spot a memory leak right away (but that doesn't mean it's not there). Could you post your code (or put it in a gist and post the link)?

**Comment by asinverse** [comment]
It seems that my system problem, related to https://discussions.apple.com/thread/5489041?start=0&tstart=0. I had over 3GB memory swapped to the hard disk and I thought my app was swapped. After solving that problem, the app works well. Thank you for your help @prust :)

**Comment by prust** [comment]
@asinverse: No problem, glad you got it figured out!
