### ISSUE TITLE
Throttling cache memory usage?

### ISSUE THREAD

**Issue by lesmo** [louischatriot/nedb#251]
According to the ```README.md``` file, **NeDB** keeps a copy of the entire database in memory. A possibility of _disabling_ this functionality has been hinted in the readme, but can a "throttling" of the size of this cache in memory be done?

I haven't dived into the code, so I'm not sure how complex would that be. At least _disabling_ that cache could be helpful.

^_^ thanks!

**Comment by louischatriot** [comment]
This is not possible. We can disable completely the cache but in that case you can only insert documents in the database, not find, update or delete, so in that case you can only use NeDB as a logging device. If you want the full DB you need the cache.
