### ISSUE TITLE
Cannot call method 'sort' of undefined

### ISSUE THREAD

**Issue by mildfuzz** [louischatriot/nedb#260]
Trying to adapt add sorting to my query, but getting the above error.

Code here:
```js
var db = { list: new nedb({ filename: databaseSource, autoload: true }) };
db.list.find({}).sort({'memo': 1}).exec(function(err, docs){
      console.log(docs);
})
```

**Comment by bhaveshgohel** [comment]
@mildfuzz : Try sort({memo: 1}) like this, i.e without quotes.
Hope this helps.

- BG

**Comment by bhaveshgohel** [comment]
@mildfuzz : Try sort({memo: 1}) like this, i.e without quotes.
Hope this helps.

**Comment by mildfuzz** [comment]
No joy, same error.

**Comment by louischatriot** [comment]
@bhaveshgohel  I don't see how removing the quotes could change anything, it's the same ...

@mildfuzz This should work. I copied pasted your code and it does work. You most probably don't have a recent enough version of nedb. Closing this, reopen if I'm wrong.

**Comment by mildfuzz** [comment]
I did wonder, tried it anyway! :)




Yep, that’s the ticket. Was on 0.8, thanks!


—
