### ISSUE TITLE
Exclude browser version from npm distribution

### ISSUE THREAD

**Issue by felicienfrancois** [louischatriot/nedb#263]
browser-version weight 7MB, which is quite a lot.

It should be excluded from npm distribution (Maybe with the `files` field of package.json https://docs.npmjs.com/files/package.json#files)

**Comment by louischatriot** [comment]
It's only the case after building the browser version, otherwise it's around 400KB. In any case disk space is cheap so I don't see a need for this.

**Comment by felicienfrancois** [comment]
Well, in 1.1.1, the result of `npm install` was more than 7MB (the browser version was automatically built).
Since your last update it is 1MB, so it's much better. Thank you for the fix.

The need is for redistribution. When using it with [nwjs](https://github.com/nwjs/nw.js) for example.
