### ISSUE TITLE
datafile is overwritten or recreated when I restart app.

### ISSUE THREAD

**Issue by praves77** [louischatriot/nedb#266]
I have written NodeWebKitApp in which I save user's data (like name, uid and settings). I can insert a document without any problem and I can see its content. The file size is about 2KB.

But, if I close the app and then re-open it, the saved data is lost and I see a file size of 0 bytes.

On debugging, I discovered that overwriting of data-file hapeens when the following line is executed to construct datastore:

db = new Datastore({ filename: myPath, autoload: true });

I tried to debug nedb/persistance.js but could not resolve the issue. I also tried loading the database manually by calling loadDatabase(function(err) {}) but without success.

Here is a snippet of code:

var Datastore = require('nedb'),  
..
..
..                                                               
myPath = "<User-Home>/.myApp/user.db",  // yes, its ".myApp" to make it hidden folder
db = new Datastore({ filename: myPath, autoload: true });

------------
I have also tried followings:
1.  I tried with non-hidden folder but same issue. 
2. On further debugging, I am seeing that loadDatabase is creating data-file thereby causing loss of old data. And folder '<User-Home>/.myApp/' containing data-file is not re-created.

BTW, its nice work and kudos to contributors.

**Comment by praves77** [comment]
Issue was in my method which was being earlier used to save data (as a string) to localstorage. I was using same method to store data to NeDB and hence it was inserting document as string not JSON/object/collection of objects. My Bad, I am closing this issue as not bug.

**Comment by Jovonni** [comment]
this still happens btw

**Comment by Jovonni** [comment]
just on using loadDatabase, or autoload, the db is recreated, and overwritten

**Comment by louischatriot** [comment]
Data file being overwritten on startup is the expected behavior as explained in the readme. If you think you have a bug e.g. data loss please show the shortest snippet of code that triggers the issue so that we can look into it.
