### ISSUE TITLE
It seems NEDB forget about latest entries

### ISSUE THREAD

**Issue by dmpost** [louischatriot/nedb#269]
I have a weird issue.
which is not easy to reproduce.

For example I have 3 entries in DB file when I start node app.
I add 2 new entries at runtime.
I see 5 entries in the DB file, everything works perfectly until some moment.

Maybe the app goes to sleep and forget something, I don't understand exactly what happens,
but after 10-15 minutes, it still shows 5 entries in the file, but only 3 in memory.

Here is the code that shows me the that 4 and 5 are undefined,
and only 3 in DB
```
db.find({ _id: _order }, function (err, docs) {

			console.log(" -- docs[0] ", docs[0]);

			if(!docs[0]){
                      
				db.find({}, function (err, docs) {
					for(var i=0; i<docs.length; i++){
						console.log("docs[i] ", docs[i]);
					}
				});
			}

});
```
I need to reload the app to make it see all 5.
I've added compaction (compactDatafile()) after each insert and update, but it doesn't help.
Any ideas?

**Comment by szwacz** [comment]
I'm afraid without you being able to provide full snippet of code to reproduce the issue there is not much we can do.

**Comment by dmpost** [comment]
OK,
I've made simplified example,
I think it happens because of the cluster module (cluster.fork()), which set up multiple node workers that listen on a single port.

How to reproduce:
- start the program in node
- add couple of entires via browser 
http://localhost:1337/db/insert/?text=test&id=1
http://localhost:1337/db/insert/?text=test&id=2
- make sure you can find them - http://localhost:1337/db/find/?id=2
- restart the program
- add entries 3 and 4
- now you have 1 and 2 entries that NEDB never forget and 3 and 4 that could be forgotten in 15-20 minutes (however they persist in file)

It's happens not every time, you may need to try those steps several times to reproduce the problem.

If you catch the problem, NEDB can add another instance with the same ID avoiding 'uniqueViolated' error and even lost some entries from DB file (didn't happen for me in the small example, but I think it is related problem).

I've managed to reproduce it on a website Linux sever, Win and Mac machines with different Node versions.
```

var http = require('http'),
    url = require("url"),
    cluster = require('cluster'),
    numCPUs = require('os').cpus().length,
    Nedb = require('nedb');

var db = new Nedb({ filename: 'my_db', autoload: true });


if (cluster.isMaster) {
    for (var i = 0; i < numCPUs; i++) {
        cluster.fork();
    }
}else {

    http.createServer(function (req, res) {

        var url_parts = url.parse(req.url, true);
        var uri = url_parts.pathname;

        db_request(uri, res, url_parts.query);

        res.writeHead(200, {'Content-Type': 'text/plain'});


    }).listen(1337, '127.0.0.1');
}

function db_request(uri, res, query){

    if(uri === '/db/insert/'){

        db.insert( {_id: query.id, text: query.text}, function (err) {
            if(!err){
                res.write("added "+query.id);
            }else{
                res.write("not added");
            }
            res.end();
        });

    }else if(uri === '/db/find/'){

        db.find({ _id: query.id }, function (err, docs) {

            res.write("found docs[0] "+ JSON.stringify(docs[0])+"\n\n");
            if(docs[0]){
                res.end();
            }else{
                db.find({}, function (err, docs) {
                    for(var i=0; i<docs.length; i++){
                        res.write("docs[i] "+ JSON.stringify(docs[i])+"\n");
                    }
                    res.end();
                });
            }

        });
    }
}

console.log('Server running at http://127.0.0.1:1337/');
```

**Comment by dmpost** [comment]
Also it shows following errors,
```
...nedb\lib\datastore.js:67
    if (err) { throw err; }
                     ^
Error: EPERM, rename 'my_db'
    at Error (native)

    if (err) { throw err; }
                     ^
Error: ENOENT, rename 'my_db~'
    at Error (native)

```

**Comment by szwacz** [comment]
`EPERM` means the nodejs process doesn't have permissions to touch given file. So it can't store new data you wanted to write. Could it be that solution to your problem is that simple? :)

**Comment by dmpost** [comment]
I'm not sure if these errors affect on the problem at all.
When I see that errors, everything is working fine, until some moment.
Maybe these errors mean that several workers have problem to access the same files.

**Comment by szwacz** [comment]
I'm confused what `cluster` does. (Sorry, not actually a backend guy here). Is it paralelization? I'm sure you know NEDB doesn't work concurrently. Right? https://github.com/louischatriot/nedb/issues/222

**Comment by dmpost** [comment]
I didn't think if  I need concurrent access to NEDB.
I just want to use all 8 cores of server CPU instead of 1.

I use one server (http.createServer()) to handle multiple requests,
only few (very few) of them need access to NEDB. 

Good explanation on what cluster does - https://keyholesoftware.com/2015/01/26/improve-node-js-performance-by-turning-it-into-a-clusterfork/

Here is what might explain our issue:
"When multiple processes are all accept()ing on the same underlying resource, the operating system load-balances across them very efficiently. There is no routing logic in Node.js, or in your program, and ```no shared state between the workers. Therefore, it is important to design your program such that it does not rely too heavily on in-memory data objects``` for things like sessions and login."

If I right understand NEDB don't access the file each time, it relies on cache in memory.
So if one worker has the cache in memory, other workers might not.

Any ideas ?
Maybe an option to turn off the memory cache?

**Comment by louischatriot** [comment]
Which is why we are saying this approach is not compatible with Nedb. There is no plan not to use the cache, and to be frank what you're doing looks a lot like premature optimization. Also, if you do need to cluster your Node server then you need a full blown database solution such as MongoDB, definitely not NeDB.
