### ISSUE TITLE
License attribute in package.json is misspelled

### ISSUE THREAD

**Issue by NetherNarwhal** [louischatriot/nedb#270]
Not a big deal, but it is currently spelled "licence" in the package.json and should be "license". Noticed just because it confuses the parser that we use to validate that all modules use a corporate approved license. Thanks!

**Comment by NetherNarwhal** [comment]
Same misspelling in binary-search-tree module.

**Comment by NetherNarwhal** [comment]
Should clarify the above, misspelled isn't the right word. It is a valid spelling outside of the US, however it is not the commonly used spelling in the package.json.

**Comment by louischatriot** [comment]
Indeed thanks, this is now fixed.

**Comment by ness-EE** [comment]
Not sure it's an American thing - Licence is a noun, license is a verb
