### ISSUE TITLE
callback to Persistence.prototype.compactDatafile

### ISSUE THREAD

**Issue by jboulhous** [louischatriot/nedb#272]
Hello,
thank you for sharing this module.
I would like to use it in a simple app, and i think i may backup my files with google drive, by copying my data files to some googledrive folder. so i thought i may compactDatafile manualy and copy it, or i may listen to app close and compactDatafile and copy it.
it would be great if we could have a callback to run after compactDatafile have finished.
i have created this pr https://github.com/louischatriot/nedb/pull/271

**Comment by jboulhous** [comment]
Hello,
may be we could emit an event on some eventemitter.
please consider providing a way to know when compaction is done.
regards,
Jamal

**Comment by jnovack** [comment]
From the docs...

> You can manually call the compaction function with `yourDatabase.persistence.compactDatafile` which takes no argument. It queues a compaction of the datafile in the executor, to be executed sequentially after all pending operations. **The datastore will fire a `compaction.done` event once compaction is finished.**
