### ISSUE TITLE
How can I completely stub MongoDB?

### ISSUE THREAD

**Issue by gobwas** [louischatriot/nedb#273]
Hello!

In this [post](http://blog.mongodb.org/post/55693224724/nedb-a-lightweight-javascript-database-using) at MongoDB blog I found idea, that NeDB for Mongo is like SQLIte for MySQL and others. So, I just wanted to know, is it possible to quickly switch between these DBs (mongo and ne) without rewriting code?

For node, there is a node-mongodb-native API library. But at first time, API of NeDB looks like not compatible with it..

**Comment by louischatriot** [comment]
NeDB is almost API compatible with MongoDB, not completely. The CRUD api is compatible, I think indexes are not. In a nutshell if you want to switch from one to the next it's going to be quite quick.

**Comment by gobwas** [comment]
Quick, but with code =)
CRUD API - does not have `insertMany` and brothers. 

Okay, anyway thanks :beers:
