### ISSUE TITLE
Can't return a value from findOne's callback

### ISSUE THREAD

**Issue by woganmay** [louischatriot/nedb#274]
I'm trying to pull a document out to work with it:

```js
var foundDocument = null;

db.findOne({ domain: 'world', type: 'server', ip: ip }, function(err, doc){
  foundDocument = (doc == null) ? false : doc;
});

console.log(foundDocument); // expected: object/false | actual: null
```

That foundDocument needs to be returned so I can work with it elsewhere. Is there another way to get a document out like this?

**Comment by woganmay** [comment]
I ended up rewriting this part of my code to put db.findOne near the top, but it would still be useful to be able to extract a document in this way.

**Comment by louischatriot** [comment]
Your console log statement should be in the callback, that's the basic of
async programming ...

**Comment by woganmay** [comment]
I'm using console.log to demonstrate the output. I need to return that foundDocument.

**Comment by louischatriot** [comment]
As I said it's got nothing to do with nedb you have to learn async
programming first ...

**Comment by woganmay** [comment]
Maybe you have to learn how to deal with synchronous reads first, lol - like most other database libraries on the planet. But it's fine, I know how your code works now.
