### ISSUE TITLE
admin tool

### ISSUE THREAD

**Issue by nite** [louischatriot/nedb#275]
I'd like to use nedb as a simple cms - are you aware of any db admin/editor UI that is compatible?

**Comment by marshallswain** [comment]
Not a bad idea.  I have been working, slowly, on a data management tool that will allow (eventually) managing many different types of servers by adding adapters to it.  I'm surprised at myself for overlooking Nedb as an adapter for it.

Would you mind creating an issue for it in my github repo?
https://github.com/marshallswain/amity

I want to eventually package it as a node-WebKit standalone app, and Nedb would be an obvious choice to make it happen.

**Comment by louischatriot** [comment]
The easiest would probably to adapt the code from Mongo-Edit which is a REST admin tool for Mongodb I coded a few years ago. https://github.com/louischatriot/mongo-edit
