### ISSUE TITLE
incase sensitive DB search 

### ISSUE THREAD

**Issue by karna41317** [louischatriot/nedb#279]
I'm trying using regex to search my database using url queary params. For example, queary param is "hello", and my database's data is "Hello". How can I have it match regardless of it's casing?
Thanks in advance,

**Comment by santiblanko** [comment]
Maybe you need something like that.
{
    key: new RegExp(value, 'i')
 }

**Comment by louischatriot** [comment]
That's basic javascript, regexes like /regex/i
