### ISSUE TITLE
Why does update/compacting want to have 2 versions of object in the DB?

### ISSUE THREAD

**Issue by unformatt** [louischatriot/nedb#280]
Firstly, thanks for a great library.

Seems like DB compacting prefers to leave 2 versions of a doc in the db file. For example, I created a doc then update it 2 times, the db file shows (before compacting):

```
{"name":"foo","_id":"6sptWU7spSsYm96w", n:1}
{"name":"foo","_id":"6sptWU7spSsYm96w", n:2}
{"name":"foo","_id":"6sptWU7spSsYm96w", n:3}
```

Then app is restarted and DB in compacted, the result is 
```
{"name":"foo","_id":"6sptWU7spSsYm96w", n:2}
{"name":"foo","_id":"6sptWU7spSsYm96w", n:3}
```

After one more update and compacting, the result is now:
```
{"name":"foo","_id":"6sptWU7spSsYm96w", n:3}
{"name":"foo","_id":"6sptWU7spSsYm96w", n:4}
```

It's always leaving the previous version. Is there any reason for that?

**Comment by unformatt** [comment]
Found another case where 3 are now left in the db file. The middle one is the oldest one:

```
{"name":foo","_id":"NOqb047zqMS4ASlJ","last_run":{"$$date":1432249215526}}
{"name":"foo","_id":"NOqb047zqMS4ASlJ"}
{"name":"foo","_id":"NOqb047zqMS4ASlJ","last_run":{"$$date":1432249221993}}
```
Further updates update either top or bottom doc but leave the middle doc untouched.

**Comment by unformatt** [comment]
Is this project alive? I see lots of unanswered issues.

**Comment by louischatriot** [comment]
The project is alive and the answer to your question in the readme.

**Comment by unformatt** [comment]
Can you elaborate? I see nothing in the README that indicates why 2 copies of an object would be left behind *after* compacting.

**Comment by louischatriot** [comment]
Hum indeed that's not supposed to happen, I misunderstood your question. To make sure there actually is an issue please send me a full snippet of code with actual vs expected result on your machine, so that I may run it on mines, and I'll reopen this issue.
