### ISSUE TITLE
Push in multidimensional array

### ISSUE THREAD

**Issue by slavepomme** [louischatriot/nedb#283]
Hello!	

How can I insert data in table.lignes with NEDB?

This is my Data :

    {"nom":"BDD1",
    "tables":[{
       "attributs":[],
       "lignes":[],
       "_id":"NJKbvGoN"
    }],
    "_id":"d9uIkr8opwgaf5Km"}

I tried these soluions but it does not work or it will not produce the correct result :

    nedb.bdd.update({"tables._id" : idTable}, { $push: { "tables.lignes" : "data" }}, {}, function (err)
    // No result

    nedb.bdd.update({"tables._id" : idTable}, { $push: { tables : { lignes : "data" } }}, {}, function (err)
    {"nom":"BDD1",
    "tables":[{
       "attributs":[],
       "lignes":[],
       "_id":"NJKbvGoN",
       "lignes" : ["data"]
    }
    // No good result

[Stackoverflow - Nedb - push in multidimensional array](http://stackoverflow.com/questions/30427795/nedb-push-in-multidimensional-array)

Thank you :+1:

**Comment by louischatriot** [comment]
Your code is really messy and doesn't follow the readme. I don't have the time to fix this, please work from the examples in the readme or over the internet to get to a working version.
