### ISSUE TITLE
Use nedb to store express-sessions

### ISSUE THREAD

**Issue by alexnix** [louischatriot/nedb#284]
I tried to use a nedb datastore to save express sessions (to persist over server restarts). But I got 
TypeError: Object #<Datastore> has no method 'on'

I think it woul be great to use nedb to store passport.js sessions, for example.

**Comment by louischatriot** [comment]
Well there is this for express sessions: https://github.com/louischatriot/connect-nedb-session

But it's not maintained anymore. For passport.js I'm not planning on creating a module as I don't have the time. Please feel free to do so though.

**Comment by zevero** [comment]
It works great with Express 4 and I don't know what is the fuss about ... 
https://github.com/louischatriot/connect-nedb-session/issues/3

That said, there is no real advantage on using nedb over standard file store...

**Comment by louischatriot** [comment]
There is one if you need sessions to be persisted through application reloads, but I don't have the time to maintain this project.
