### ISSUE TITLE
limit doesn't work with sort

### ISSUE THREAD

**Issue by jasonslyvia** [louischatriot/nedb#287]
The following code shows how I query data from nedb:

```
db.find(newQuery).sort({ rent: -1}).skip((page - 1) * pageSize).limit(pageSize).exec((err, houses) => {
  // deal with result
});
```

The query works fine at first time, it returns 10 records because `pageSize` has been set to 10. However when `page` changes to `2`, the query returns all the result.

First log:
```
query { rent: { '$gt': 0, '$lt': 99999999 } }
skip 0
limit 10
```

Second log:
```
query { rent: { '$gt': 0, '$lt': 99999999 } }
skip 10
limit 10
```

No idea why the second query returns all the result other than 10.

node: 0.10.31
nedb: 1.1.2
OS: OS X 10.10.2

**Comment by louischatriot** [comment]
Please supply a code snippet showing the entire behavior, including how you insert docs in the db, expected vs actual logs and I'll reopen

**Comment by tambovchanin** [comment]
The same problem

**Comment by louischatriot** [comment]
Please follow thé bug reporting guidelines when reporting à bug
Le 23 mars 2016 10:50 PM, "Denis Shiryaev" <notifications@github.com> a
écrit :

**Comment by kavi87** [comment]
I thought there was an issue as well but the problem was type conversion. Be sure to pass numbers to the limit and skip methods and not a string (req.params values are string, most notably).

**Comment by pixelpax** [comment]
@kavi87 You're my hero-- I ran into the exact same problem, also from req.params in express, thanks for posting the solution!

Seems like this would be a common mistake, the most common situation I can imagine using `limit` would make direct use of a query param. Perhaps nedb should raise an error when bogus types are passed into cursor functions @louischatriot ? Would you accept a PR doing this?
