### ISSUE TITLE
Joined request

### ISSUE THREAD

**Issue by Yimiprod** [louischatriot/nedb#289]
Is there a way to do a join in a request.
Say i have a doc
```
{
  _id: "id1",
  title: "some title",
  subdata: ['id2','id3']
}
```
Doing a request to get doc id1, and populating subdata set with others doc fetch by id in array before returning the doc id1.

**Comment by szwacz** [comment]
Don't think so. Just write few extra lines of code to get those documents after you get the first one.

BTW, NEDB is in-memory, so you don't have latency problems, so you can do those requests by yourself in very reasonable time (if that was your concern).

**Comment by Yimiprod** [comment]
Well in my case, probably because i have promisified nedb, i take around 200ms to get the first data, then another 200ms to get the other docs.
In the angularjs view you can see for a really short amount of time a white page, then first data followed by the others set of data.

**Comment by szwacz** [comment]
Do you have index on field you are searching by?

**Comment by Yimiprod** [comment]
After your comment i've indexed it, nothing seem to change, i have tested with a timer too seed how many time a request take, it take around 500ms to fetch the data.

**Comment by louischatriot** [comment]
500 ms is a huge time for one find, even with non indexed data. What's the size of your dataset?

**Comment by Yimiprod** [comment]
Extra small, only two main object atm. and 10 sub object in 4 other db (splited each type of object in dedicated db). Every request take that time

**Comment by louischatriot** [comment]
OK in that case it's not possible that it's a problem with nedb. Please copy paste a full code snippet (including inserting docs) here that takes 500 ms to run to fetch one document and I'll reopen the issue if it's also slow on my machine

**Comment by Yimiprod** [comment]
After some test when preparing you the snippet i have seen that the resquest take less and less time when the same one is repeated, like, first time we do a request based on an array, it take 400ms, then the second time we do the same it only take 32 ms.

I thinks it's because they are indexed at that moment, is there a way to force index when we set the data?

**Comment by louischatriot** [comment]
No it has nothing to do. Even 32 ms is way too much.

**Comment by Yimiprod** [comment]
Well, i have prepared an exemple... And outside my nw.js app there is far more better perfomances.
So i think i'll give up at that point. Problem not coming from NeDB.

**Comment by Yimiprod** [comment]
Return after some time, NEDB work like charm when my app is builded, so i think the perf problem only exist in dev env.
