### ISSUE TITLE
Is it possible to store reference to an object?

### ISSUE THREAD

**Issue by ReimuYome** [louischatriot/nedb#290]
Take the following snippet for example (using jQuery) :

````
var jq = $("div"); // there are a lot of div's in this page
var obj = { divGroup : 1, ref : jq };
var db = new Nedb();
db.insert( obj );
db.find({},function(err,doc){console.log(doc);}); // outputs empty array
````
 
I know it is because ````Maximum call stack size exceeded````, and apparently I am not intending to store a jQuery object property by property in the database. 

But in some cases, the objects to store are related with such complicated ones, and I want to keep the reference. So I can look up those complicated objects using simple property values  from the objects stored in the database. 

In this example, it is to say not probing properties of  ````ref```` property of  ````obj````  but just storing a reference for it.

**Comment by louischatriot** [comment]
Please read the readme, it's clearly not an intended use to store jquery objects.
