### ISSUE TITLE
Add custom backend support

### ISSUE THREAD

**Issue by rumkin** [louischatriot/nedb#292]
I wish to store binary objects in db but JSON doesn't support binary encoding. And I guess CBOR is more sufficient for me. I can create it myself but there is no custom datastore API as I see.

**Comment by louischatriot** [comment]
Not planned but you can always encode/decode your blob in base64. This will take a bit more space (1.33x the size of your array) but in most usecases that's not an issue.

Do not use utf8 to do so or you're in for some hard to debug trouble, see http://haacked.com/archive/2012/01/30/hazards-of-converting-binary-data-to-a-string.aspx/
