### ISSUE TITLE
Skip Hazard

### ISSUE THREAD

**Issue by SeanConnelly** [louischatriot/nedb#296]
This (very) minor problem tripped me up for a while.

In cursor.js the skip logic looks like this...

res = res.slice(skip, skip + limit);

This looked to work fine for skip=0 and limit=10, but then when I tried skip=10 and limit=10 I received back my entire dataset.

I realised after a while that I was passing in strings and not integers, skip + limit was producing "1010" and not 20. I'm sure I'm not the first to lose an hour looking at this, perhaps the following change would be helpful for others...

res = res.slice(skip, +skip + +limit);

**Comment by louischatriot** [comment]
Thanks for reporting, but that's more a JS shortcoming (no typing) than something I want to change in nedb, as I think a JS programmer needs to always know and check variable type, since JS won't do it for him.
