### ISSUE TITLE
limit does not work on large datasets

### ISSUE THREAD

**Issue by dariosalvi78** [louischatriot/nedb#297]
for some strange reason, on a large dataset (>1000 elements) when using skip + limit does not work correctly.
Concretely: skip 0, limit 10 gives 10 elements, but skip 10, limit 20 gives 1000 elements!
Any reason for it?

**Comment by louischatriot** [comment]
It shouldn't. You're probably passing strings not numbers, please provide code snippet and I'll reopen.

**Comment by dariosalvi78** [comment]
you're right, I was passing limit and skip as strings not integers!
