### ISSUE TITLE
Unexpected behaviour sorting elements with letters and numbers

### ISSUE THREAD

**Issue by legionsra** [louischatriot/nedb#298]
This is not a big problem, it should be a little mistake on the code but for some people this is probably essential and a must to fix it.

The example to explain this is quite easy.

You have 10,000 records, with a field called "name" automatically generated, starting by "A-name1" to "A-name10000"

Expected result of the first 7 elements using `db.find().sort({ name: 1})`:
"A-name1"
"A-name2"
"A-name3"
"A-name4"
"A-name5"
"A-name6"
"A-name7"

Result received:
"A-name1"
"A-name10"
"A-name100"
"A-name1000"
"A-name10000"
"A-name1001"
"A-name1002"

The problem on this is that the function sorting the result gives more relevance on having more characters  than having everything sorted with less characters, when this second option is the human thinking behaviour.
As i said, It should not be a huge problem to fix this minor error.
Thank you for considering it.

**Comment by louischatriot** [comment]
That's normal, you are sorting strings.

**Comment by cgestes** [comment]
google natural sorting for an explanation.

**Comment by legionsra** [comment]
Interesting, i found some related docs about it. i really apreciate it.
I was using other databases before and they use the human readable way of sorting, but it seems that this way is the computer correct way, and internally is how most of the fastest databases works.
Thank you all anyway, it wasn't a real issue but a personal suggestion.
