### ISSUE TITLE
Document inserted on update() and with upsert set to false

### ISSUE THREAD

**Issue by stefanodefaria** [louischatriot/nedb#300]
Whenever you update a document using $set, it always creates a copy of that document with the new inserted property. The old document (the one that doesn't have that property) stays on the database.
This creates documents with duplicate_id's.

This code can reproduce the problem:
-------------------START-------------------
var Datastore = require('nedb');
var async = require('async');
var dbPath = "test.nedb";
var db = new Datastore({ filename: dbPath });
function loadDB(cb){
    db.loadDatabase(function(err){
        cb();
    });
}
function populateDB(cb){
    db.insert({_id: 1, planet: "Earth"}, function(err, newDocs){ cb(); });
}
function updateDB(cb){
    db.update({ _id: 1}, { $set: { system: 'solar system' }},{}, function (err, newDocs) { cb(); });
}
async.series([loadDB, populateDB, updateDB], function(){console.log("end")});
-------------------END-------------------
Output file:
{"_id":1,"planet":"Earth"}
{"_id":1,"planet":"Earth","system":"solar system"}

**Comment by louischatriot** [comment]
Seems like something covered in the readme.
