### ISSUE TITLE
New data update issue 

### ISSUE THREAD

**Issue by pushpendrachauhan** [louischatriot/nedb#307]
Whenever i am querying db for all entries in db i am not getting the update data.

Lets suppose i made a connection to db and named is a "con" in the starting and db is having 10 fields, Then i run my script and some more data is populated to db lets say 20 rows, Now when i use same connection "con" to query db to list all rows in db, I get only 10 records which was already present in db in the starting but we are not getting that 20 new rows which was inserted.

To get rid of this problem we are making new connection to db just before the list query and assigning it to "con" variable. Here is the example of problem we are facing.
 
// new connection to db , db already having 10 records in it
var con=new Datastore({ filename: __dirname + '/db.json', autoload: true });

//some insert statement now db is having 10+20 total 30 records.

// querying the db to get all rows
con.find({}).sort({ IN: 1 }).exec(function (err, docs) {
// getting only 10 records but total 30 records are present in db
});

// querying the db with new connection to db
con=new Datastore({ filename: __dirname + '/db.json', autoload: true });
con.find({}).sort({ IN: 1 }).exec(function (err, docs) {
// getting all records old+new = 30 records 
});

I am assuming it is due to the fact that it loads the (.json) file in memory when connection was made first time, New records comes later on so they are not present in memory and query returns the records which was loaded first time.

**Comment by louischatriot** [comment]
Most probably an issue in your code. Please copy paste a working code snippet with expected vs actual result and I'll reopen if the issue is valid.
