### ISSUE TITLE
Primary key works oddly with arrays/objects

### ISSUE THREAD

**Issue by lostcolony** [louischatriot/nedb#309]
nedb allows you to specify a primary key with an array or object, however, it doesn't work at all like one would expect.

I was using nedb with some indices (don't know if that matters). Inserting items that looked like - 

{"_id" : {"a" : 1, "b" : 1}, "etc" : "stuff"}
{"_id" : {"a" : 1, "b" : 2}, "etc" : "more_stuff"}

and then restarting, upon loading the DB, would cause the data to be collapsed down to one or the other of the entries, rather than both.

A similar thing happened when using an array, except that at least errored, albeit only due to constraint violations (rather than rejecting them outright). Trying to insert the following -

{"_id" : [1, 1], "etc" : "stuff}
{"_id" : [1, 2], "etc" : "more stuff"}

would lead to a unique constraint violation. 

A fix would be to reject _ids that are arrays/objects, or at least to indicate in the docs what forms are supported.

**Comment by louischatriot** [comment]
That's indeed a difference with mongodb. I added a note in the readme.
