### ISSUE TITLE
NeDB didn't update the records

### ISSUE THREAD

**Issue by efirvida** [louischatriot/nedb#310]
Hi I don't know why this function didn't do anything, even don't show anything on the console, and the callback function didn't work , Sorry if I made an obvious mistake I'm new with node js and NeDb.

here is my update function:

    var Datastore = require('nedb'),
        db = {
            games: new Datastore({filename: './backend/data/games.db', autoload: true})
        };
        
    var models = { 
         games : {
                  update: function (query, update, options, callback) {
                               db.games.update(query, update, options,callback)
                 }
                }
               }
    module.exports = models;

and I called with:

    var models = require('./models');
        
    models.games.update({_id = game_id}, {$set: {fen: game.fen(), pgn: game.pgn()}}, {}, function(err,numDocs,docs){
          if (err){
             console.log(err);
          } else {
             console.log(numDocs);
             console.log(docs);
          }
        });

mi database looks like:

    {"_id":"Egw17uRnAd5sdaKXVlOfxRQ6zr4VnSvFghiXkXHyCi9oiDMqDS","startpos":"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1","fen":"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1","pgn":"","w_id":"","b_id":""}
    {"_id":"6ZlTTQgk2hEhorTGeTV45kkRsUvrxfmROiCJMqLRQoTnvabhqK","startpos":"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1","fen":"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1","pgn":"","w_id":"","b_id":""} 

and the variables for the query

    game_id = '6ZlTTQgk2hEhorTGeTV45kkRsUvrxfmROiCJMqLRQoTnvabhqK'
    game.pgn() = '1. e4 e5 2. Nf3'
    game.fen() = 'rnbqkbnr/pppp1ppp/8/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R b KQkq - 1 2'

and if I put all the code together not in separated module works perfectly 

    var Datastore = require('nedb'),
        db = {
              games: new Datastore({filename: './backend/data/games.db', autoload: true})
              },
        models = { 
         games : {
                  update: function (query, update, options, callback) {
                               db.games.update(query, update, options,callback)
                 }
                }
               };

    models.games.update({_id : game_id}, {$set: {fen: game.fen(), pgn: game.pgn()}}, {}, function(err,numDocs,docs){
       if (err){
           console.log(err);
       } else {
           console.log(numDocs);
           console.log(docs);
       }
    });

maybe is something with been working in separated module

**Comment by louischatriot** [comment]
Please provide a code snipper with actual vs expected result and I'll reopen if this seems like a nedb bug.

**Comment by efirvida** [comment]
mi models.js looks like
var Datastore = require('nedb'),
    db = {
        users: new Datastore({filename: './backend/data/users.db', autoload: true}),
        games: new Datastore({filename: './backend/data/games.db', autoload: true})
    };


var models = {
    users: {
        create: function (user, email, password, callback) {
            db.users.insert({user: user, email: email, password: password}, callback);
        },
        count: function (query, callback) {
            db.users.count(query, callback);
        },
        update: function (query, update, options, callback) {
            db.users.update(query, update, options, callback);
        },
        list: function (callback) {
            return db.users.find({}).exec(callback);
        },
        remove: function (id, callback) {
            db.users.remove({_id: id}, callback);
        },
        find: function (query, callback) {
            return db.users.find(query).exec(callback);
        },
        findOne: function (query, callback) {
            return db.users.findOne(query).exec(callback);
        }
    },
    games: {
        create: function (id, startpos, fen, pgn, w_id, b_id, callback) {
            db.games.insert({_id: id, startpos: startpos, fen: fen, pgn: pgn, w_id: w_id, b_id: b_id}, callback);
        },
        update: function (query, update, options, callback) {
            db.games.update(query, update, options, function(err,numDocs,Docs){
                if (!err){
                    console.log(numDocs);
                    console.log(Docs);
                }else{
                    console.log(err);
                }
            });
        },
        list: function (callback) {
            return db.games.find({}).exec(callback);
        },
        remove: function (id, callback) {
            db.games.remove({_id: id}, callback);
        },
        find: function (query, callback) {
            return db.games.find(query).exec(callback);
        },
        findOne: function (query, callback) {
            return db.games.findOne(query).exec(callback);
        }
    }
};

module.exports = models;

then the calling from server.js as

var models = require('./models');

models.games.create('6ZlTTQgk2hEhorTGeTV45kkRsUvrxfmROiCJMqLRQoTnvabhqK', 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', '', '', '');

the the database looks like
{"_id":"6ZlTTQgk2hEhorTGeTV45kkRsUvrxfmROiCJMqLRQoTnvabhqK","startpos":"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1","fen":"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1","pgn":"","w_id":"","b_id":""} 

when use:

models.games.update({_id: '6ZlTTQgk2hEhorTGeTV45kkRsUvrxfmROiCJMqLRQoTnvabhqK'}, {$set: {fen: 'r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 5 4', pgn: '1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. O-O'}}, {}, function(err,numDocs,docs){
      if (err){
         console.log(err);
      } else {
         console.log(numDocs);
         console.log(docs);
      }
    });

I sepect to have 

{"_id":"6ZlTTQgk2hEhorTGeTV45kkRsUvrxfmROiCJMqLRQoTnvabhqK","startpos":"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1","fen":"r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 5 4","pgn":"1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. O-O","w_id":"","b_id":""} 

but have 
{"_id":"6ZlTTQgk2hEhorTGeTV45kkRsUvrxfmROiCJMqLRQoTnvabhqK","startpos":"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1","fen":"rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1","pgn":"","w_id":"","b_id":""}

**Comment by louischatriot** [comment]
Please provide a single, self-containing code snippet that shows the behavior so that I can test in less than 2 minutes. It should be as short as possible.

**Comment by efirvida** [comment]
The models.js file

        var Datastore = require('nedb'),
            db = {
                games: new Datastore({filename: 'database.db', autoload: true})
            };


        var models = {
            games: {
                create: function (id, startpos, fen, pgn, w_id, b_id, callback) {
                    db.games.insert({_id: id, startpos: startpos, fen: fen, pgn: pgn, w_id: w_id, b_id: b_id}, callback);
                },
                update: function (query, update, options, callback) {
                    db.games.update(query, update, options, callback)
                }
            }
        };

        module.exports = models;

the run update.js file

        var models = require('./models');

        models.games.create('6ZlTTQgk2hEhorTGeTV45kkRsUvrxfmROiCJMqLRQoTnvabhqK', 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', '', '', '');

        models.games.update({_id: '6ZlTTQgk2hEhorTGeTV45kkRsUvrxfmROiCJMqLRQoTnvabhqK'}, {$set: {fen: 'r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 5 4', pgn: '1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. O-O'}}, {}, function(err,numDocs,docs){
            if (err){
                console.log(err);
            } else {
                console.log(numDocs);
            }
        });


the spected equivalent working result on single file

        var Datastore = require('nedb'),
            db = {
                games: new Datastore({filename: 'database.db', autoload: true})
            };

        db.games.insert({_id:'6ZlTTQgk2hEhorTGeTV45kkRsUvrxfmROiCJMqLRQoTnvabhqK', startpos:'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', fen:'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', pgn:''});

        db.games.update({_id: '6ZlTTQgk2hEhorTGeTV45kkRsUvrxfmROiCJMqLRQoTnvabhqK'}, {$set: {'fen': 'r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 5 4', 'pgn': '1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. O-O'}}, {}, function(err,numDocs){
            if (err){
                console.log(err);
            } else {
                console.log(numDocs);
            }
        });

**Comment by efirvida** [comment]
The models.js file

        var Datastore = require('nedb'),
            db = {
                games: new Datastore({filename: 'database.db', autoload: true})
            };


        var models = {
            games: {
                create: function (id, startpos, fen, pgn, w_id, b_id, callback) {
                    db.games.insert({_id: id, startpos: startpos, fen: fen, pgn: pgn, w_id: w_id, b_id: b_id}, callback);
                },
                update: function (query, update, options, callback) {
                    db.games.update(query, update, options, callback)
                }
            }
        };

        module.exports = models;

the run_update.js file

        var models = require('./models');

        models.games.create('6ZlTTQgk2hEhorTGeTV45kkRsUvrxfmROiCJMqLRQoTnvabhqK', 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', 'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', '', '', '');

        models.games.update({_id: '6ZlTTQgk2hEhorTGeTV45kkRsUvrxfmROiCJMqLRQoTnvabhqK'}, {$set: {fen: 'r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 5 4', pgn: '1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. O-O'}}, {}, function(err,numDocs,docs){
            if (err){
                console.log(err);
            } else {
                console.log(numDocs);
            }
        });


the spected equivalent working result on single file

        var Datastore = require('nedb'),
            db = {
                games: new Datastore({filename: 'database.db', autoload: true})
            };

        db.games.insert({_id:'6ZlTTQgk2hEhorTGeTV45kkRsUvrxfmROiCJMqLRQoTnvabhqK', startpos:'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', fen:'rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', pgn:''});

        db.games.update({_id: '6ZlTTQgk2hEhorTGeTV45kkRsUvrxfmROiCJMqLRQoTnvabhqK'}, {$set: {'fen': 'r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQ1RK1 b kq - 5 4', 'pgn': '1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5 4. O-O'}}, {}, function(err,numDocs){
            if (err){
                console.log(err);
            } else {
                console.log(numDocs);
            }
        });
