### ISSUE TITLE
Clientside Persistence: IndexedDB

### ISSUE THREAD

**Issue by martindale** [louischatriot/nedb#311]
As LocalStorage has an upper limit to the amount of data stored (and it is relatively low), we should switch to using IndexedDB as the back-end for persistence in the client-side.

**Comment by louischatriot** [comment]
That's right indeed, thanks for pointing out. It should fallback to localStorage for older browsers though (for IE only version 10 supports IndexedDB)

**Comment by wishabhilash** [comment]
Are we supporting IndexedDB??

Am a bit tired of PouchDB for it's querying capabilities. It's plain and simply un-intuitive. It has a beta plugin for MongoDB like query but those plugins simply are not supported or RequireJS.

Any plans on this line???

Thanks. :)

**Comment by louischatriot** [comment]
Not a lot of time to work on it these days but I'd gladly accept pull requests on this. The way I see it there is only one file that needs to be modified, the browser specific version of storage.js (in \browser-version\browser-specific\lib)

**Comment by wishabhilash** [comment]
@louischatriot : Thanks for the prompt reply. Even am not getting nuf time. :-/

**Comment by louischatriot** [comment]
As of v1.4, NeDB automatically selects the best method to persist data on the browser (IndexDB then WebSQL then localStorage), so the limit is removed. WARNING: it's not back compatible with v1.3, but that should not be a major issue as user apps can resync entirely.

**Comment by martindale** [comment]
Awesome!  @ChangeTip, give @louischatriot 10,000 bits for making this happen.

**Comment by changetip** [comment]
Hi @louischatriot, @martindale sent you a tip worth 10,000 bits (10,000 bits/$3.80), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/916800)**.



**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by louischatriot** [comment]
Thanks :)
