### ISSUE TITLE
adding a timestamp/created date on upsert

### ISSUE THREAD

**Issue by southbite** [louischatriot/nedb#316]
HI there - fantastic module, thank you so much! One feature I would like to see would be for us to be able to specify a special timestamp filed on upsert, ie:
```javascript
 db.update({"username":username}, userdata, {upsert:true}, function(err, response) {
```
it would be awesome if the user object didn't exist in the system, and it got auto-created, we could somehow have the system give it a created field/timestamp. 

one of the solutions we are considering, is updating the part of nedb that creates your unique id's to contain a timestamp as part of the id, but it would be really nice if this could be a configurable feature and we didn't have to run off a branch. If something already exists that you know of, let me know - or I will do a bit of work on my side and see if you wouldn't do a pull request.

**Comment by louischatriot** [comment]
There is no such facility built-in and I think it's too specific to warrant a PR (you could simply trigger an update to add the timestamp if the document was upserted).

That said the idea of using time-based _ids has come up time and again and could definitely be a good option for several projects. I don't have time to work on it as it would require the ability to give users the choice to select their own _id generator on db creation, time-based ans random base64 being two possibilities. For the time based as it's not possible to get more than precision to the millisecond in a coherent cross platform way in JS it could be millis + xxxx where xxxx is a counter to avoid duplicates. I can review a PR of this.

**Comment by southbite** [comment]
Cool! We solved it the nasty way for now, mongo has a thing that does this
called $setOnInsert - which I think is where I would go if I was to do a
PR, I can see now there was a previous post for this:
https://github.com/louischatriot/nedb/issues/108, one could also have a
composite key - where the first characters are the utc time, and the rest
are random.

I'll have a look when I have time - but thanks again, this is a fantastic
library - we are doing something exciting with it, will update you when it
is all polished.

On Thu, Sep 17, 2015 at 2:28 PM, Louis Chatriot <notifications@github.com>
wrote:

> There is no such facility built-in and I think it's too specific to
> warrant a PR (you could simply trigger an update to add the timestamp if
> the document was upserted).
>
> That said the idea of using time-based _ids has come up time and again and
> could definitely be a good option for several projects. I don't have time
> to work on it as it would require the ability to give users the choice to
> select their own _id generator on db creation, time-based ans random base64
> being two possibilities. For the time based as it's not possible to get
> more than precision to the millisecond in a coherent cross platform way in
> JS it could be millis + xxxx where xxxx is a counter to avoid duplicates. I
> can review a PR of this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/louischatriot/nedb/issues/316#issuecomment-141064641>.
>



-- 

SIMON BISHOP

DIRECTOR

+27 (0) 83 282 0703

|     simon@tenacious.digital <brianna@tenacious.digital>

twitter: @_tenacious_ <http://www.twitter.com/_tenacious_>

|     skype: sjbishop

201 Salt Circle Arcade, Salt River, Cape Town, 7925

www.tenacious.digital

**Comment by louischatriot** [comment]
Sure please do :)

**Comment by louischatriot** [comment]
As of v1.3, nedb can maintain (user option `timestampData`) two fields, `createdAt` and `updatedAt`
