### ISSUE TITLE
persistent in browser. Loading an existing DB from file

### ISSUE THREAD

**Issue by vpl-profess** [louischatriot/nedb#317]
Hi,
I've created a nedb file (using nodejs) and would like to load it from my browser.
Using the following code does not work.
Nedb creates a new DB in memory and do no retrieve mine available on the file system (running locally first for test purposes).
Could you tell me if nedb support retrieving a db from a server, loading it for browsing puposes (no write need).
Thanks !

function otherDbTest() { 
    var db = new Nedb({ filename: 'myDb.nedb', autoload: true });
    db.loadDatabase(function (err) {    
    });	
    db.find({}, function (err, docs) {
        console.log("size:"+docs.length);
        console.log("element-1:"+JSON.stringify(docs));
    });      
}

**Comment by louischatriot** [comment]
I'd be happy to review this but you need to follow the bug reporting guidelines: https://github.com/louischatriot/nedb#bug-reporting-guidelines

I'll reopen once you resubmit.
