### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by Mobilpadde** [louischatriot/nedb#321]
A sample function would be neat. 

I'm in the middle of a project, and in **critical*** need of some arbitrary samples from the database, much like the *[sample](https://rethinkdb.com/api/javascript/sample/)*-function from Rethinkdb.

<sub>*Might not be true, but you know...exaggerations, yay.</sub>

**Comment by louischatriot** [comment]
That's completely out of nedb's scope and purpose. A simple
db.find.skip(random).limit(1) should do the trick

**Comment by Mobilpadde** [comment]
Oh well, thanks!
