### ISSUE TITLE
Option to define a first line of the datastore file for metadata

### ISSUE THREAD

**Issue by lukasbestle** [louischatriot/nedb#324]
**Use case**

I'm using NeDB and its (de)serialization hooks to store application data for my Electron app in AES encrypted files. The files are supposed to be self-contained like other documents (like a word processing document).

Before loading the database in my application, I need to check whether the file is compatible with my application. I also need to store metadata about the database like an iteration count for key derivation and a password hint separately from the main data to be able to read this data before initializing NeDB.

**Solution for the use case**

A possible solution would be to optionally reserve the first line of the datastore file for this information, like this: `myfiletype,100000,This is a password hint`.

**Reasons why I can't implement that solution right now**

There are two reasons why that doesn't work currently:

1. While loading the database, NeDB will pass this line to my `beforeDeserialization` hook. I would have to return nothing or throw an error to prevent NeDB from thinking it is a document, but that would increment the `corruptItems` variable in `Persistence.prototype.treatRawData`.
2. I can't reliably store the first line in the file. By using hacks like returning it from the `afterSerialization` hook, I won't be able to make sure it becomes the first line.

**Proposal for an NeDB feature**

1. NeDB could implement a new option called `firstLine`. It can either be a string or a function. The (return) value of this option will be prepended to the data while persisting the cached database.
2. If the option is set (and only then, see below), the `treatRawData` function will skip the first line of the raw data.
3. A new helper method `getFirstLine()` would read the datastore file and pass the first line of the file to a callback.

**Backwards compatibility**

If the option is not set, the first line of the file will continue to be an arbitrary NeDB document. This feature is completely optional and won't mess with existing datastores.

---

If you think that this feature is worth implementing, I can do so and send you a PR. Please let me know what you think.

**Comment by louischatriot** [comment]
Hello,

Interesting idea, and thanks for the well presented issue :)

That said I don't think such a feature should be part of Nedb, it seems to custom. I understand the appeal of self-containing data files but I think it would be much cleaner to put all the metadata in a separate data file, with a clear naming convention `my-data.meta` or whatever. It could even be another small Nedb file.

**Comment by lukasbestle** [comment]
Thanks for your reply.

I think this feature can still be part of NeDB, since the hooks are already a feature and this new feature complements them very well, especially when using encryption.

Since I need to have a single file, I have decided to implement this feature anyway. I will send you a PR, maybe it will convince you. ;)
Otherwise it will be a fork of NeDB.

**Comment by louischatriot** [comment]
Got it, I'll look for it then ;)
