### ISSUE TITLE
autoload or loadDatabase freeze on windows in Electron if file doesn't exist

### ISSUE THREAD

**Issue by aaronfrost** [louischatriot/nedb#327]
If the datafile doesn't currently exist, and I tell nedb to autoload it or I create a Datastore and tell it to `loadDatabase`, my process will hang at 99% on windows. In OSX it works fine. Not sure the diff, but it works fine.

I was trying to setup a datafile that would be empty at first. It would actually not exist. I was expecting nedb to init the file for it. It worked perfectly on OSX. On Windows... not so much. So, I have modified my code to:

```
try{
  fs.readFileSync('path/to/file', 'utf8');
}catch(){
  fs.writeFileSync('path/to/file', defaultConfig, 'utf8');
}
```

This allows my app to run on Windows and OSX. So, I am good again. But since the behavior was different for Windows and OSX, I thought it a bug, and thought I should at least document it here. Would be nice to have an `createIfAbsent` option in the `loadDatabase` option, and/or to accompany the `autoload` option. 

Either way, I love you all. *nedb* has saved me a lot of time. Thanks for all of your hard work.

**Comment by aaronfrost** [comment]
Nevermind, this is not the actual issue. I thought it was, but I am chasing something else related to nedb on windows.

**Comment by louischatriot** [comment]
OK. Nedb is tested and works on Win7 and Win8 so this one was puzzling me. If you actually do find a bug, please make sure to follow the bug reporting guidelines (see readme)

**Comment by aaronfrost** [comment]
For now, I am just doing `fs.readFileSync` and `fs.writeFileSync` because as soon as I add `autoload: true` or `loadDatabase`, windows pegs the CPU to 99% and I am stuck. If I comment out that line of code, app stays good. When I replaced it with the fs.rfs and fs.wfs, it just works as well. Not sure what the issue is. If I had a windows environment that didn't suck, I would test more. I may get back to it in a few weeks. Thanks for all you do.

**Comment by tex0l** [comment]
I am facing an issue very similar: loadDatabase takes 99%CPU and takes a huge amount of time on a Windows 7 without SP1, I'm not able to reproduce this bug on Windows 7 with SP1 (somehow...). Everything is done under VBox.
I don't have a `fs.readFileSync` nor a `fs.writeFileSync`, and this is this method that is taking a huge amount of time:
```
  loadDatabase () {
    return new Promise((resolve, reject) => {
      this.db.loadDatabase((error) => {
        if (error) reject(error)
        else resolve()
      })
    })
  }
```
I don't see why... I'm still investigating.

**Comment by tex0l** [comment]
Still not able to find a 100% of reproducing, but it seems it happens when a database file of 0kB exists, and it seems it's the crashSafeWriteFile method of storage that freezes.
