### ISSUE TITLE
Question about resource usage

### ISSUE THREAD

**Issue by dukedougal** [louischatriot/nedb#328]
I have created a very simple node.js express application.

It loads about 1 gig of JSON data into a memoryonly nedb database.

So I'm wondering what happens when I try to run this in production?

I don't know how express is deployed but presumably using some sort of web server that executes multiple express processes?

I am wondering if this means that each process will have its own one gigabyte nedb database in memory?

Is there a way to configure such that the one nedb database is shared amongst all the node.js express processes?

**Comment by louischatriot** [comment]
On x64 1GB is close to the limit. Depending on your app you may be able to load 1.2GB not much more. For these kinds of datasets you'll be better off using MongoDB.
