### ISSUE TITLE
use disk version of nedb in electron is accessing from browser process as well.

### ISSUE THREAD

**Issue by ivankarpey** [louischatriot/nedb#329]
In electron we could use disk system from browser process as well. But nedb automatically start operate as browser version. Is there any workaround which will make nedb work in disk mode when using in electron?

**Comment by lukasbestle** [comment]
If you load NeDB using `require('nedb')`, it will use Node APIs.

**Comment by ivankarpey** [comment]
I'm load it that way, than code goes through broswserify pipe and when it actually opened in application I see that IndexedDB used instead of file system.

**Comment by ivankarpey** [comment]
However I'm talking about browser part of electron since I don't want to use ipc mechanism to access db each time.

**Comment by louischatriot** [comment]
Using browserify will force the browser version with indexeddb, use `require`

**Comment by ivankarpey** [comment]
@louischatriot Could you then explain me how I could use require without browserify in inbrowser version of electron code?

**Comment by lukasbestle** [comment]
Well, you shouldn't let Browserify overwrite the `require` function of Node. There's a guide somewhere in the Electron or NW.js docs, but I can't find it.

**Comment by kdepp** [comment]
one tip when using electron + nedb + webpack:  Make sure to add 'target: "node"' in your webpack config.  otherwise nedb will use the browser-version storage, instead of the normal fs storage

**Comment by alayliercan** [comment]
@ivankarpey 

I'm using watchify, and I solved this issue by adding `--external nedb` parameter into package.json of my project. Like this: 
`watchify --external nedb app/index.js -t babelify -o public/js/bundle.min.js`

I'm pretty sure you can do the same thing for browserify as well, i.e. something like this:
`browserify --external nedb src/main.js -o dist/bundle.js`

**Comment by brooth** [comment]
In my case, putting `nedb` in webpack's externals did the trick:
```
externals: {
   "nedb": 'commonjs nedb',
},
```

**Comment by LukasBombach** [comment]
> In my case, putting `nedb` in webpack's externals did the trick:
> 
> ```
> externals: {
>    "nedb": 'commonjs nedb',
> },
> ```

This worked for me as well

**Comment by lanistor** [comment]
> In my case, putting `nedb` in webpack's externals did the trick:
> 
> ```
> externals: {
>    "nedb": 'commonjs nedb',
> },
> ```

useless for me, i'm using webpack 4.43

**Comment by MedoAngel** [comment]
> In my case, putting `nedb` in webpack's externals did the trick:
> 
> ```
> externals: {
>    "nedb": 'commonjs nedb',
> },
> ```

this worked for me thank you!

**Comment by fullupe** [comment]
well quick fix .....i use nedb-logger
