### ISSUE TITLE
database lost upon power loss

### ISSUE THREAD

**Issue by LowPowerLab** [louischatriot/nedb#330]
I tried the 1.4.2 version manual install hoping that the database loss issue would be fixed. Maybe I'm doing something wrong but the database is still purged if raspberry pi loses power.
The npm version is at 1.4.0, could it be updated to the latest 1.4.2 so it would be easier to update it in place?

**Comment by louischatriot** [comment]
In fact v1.4.1 and v1.4.2 are not published yet, as the persistence code is still being worked on (I actually published then unpublished it). The code on the master branch is still not ready for production, and as you are not the first one to signal this I should probably roll the commit back :) Likewise, the readme is still not accurate.

I expect this to be ready within a few days, I'll update you when it is.

Btw what project are you using nedb for ?

**Comment by LowPowerLab** [comment]
Thanks for working on this, I will be waiting for that fix since lots of people are seeing this purging issue.
I am using it for this project: https://lowpowerlab.com/gateway/
It is driving the interface (when the DB is purged, all the nodes disappear from the interface).

**Comment by louischatriot** [comment]
I pushed the new code on master, still not published on npm as it is under review. The goal of this release is to prevent any catastrophic dataloss in case of power failure. You can always lose the data in the kernel buffer caches if you unplug the Pi (it would be way too slow to wait for the OS on every write) but you cannot lose your whole database if the power chord is plugged during a loadDatabase.

Can you test again and tell me the result ?

**Comment by LowPowerLab** [comment]
Many thanks for taking care of this so quickly. I can confirm it solves the purging issue. Power loss is not a frequent expected issue, so any unflushed buffers are OK to loose, but not the whole DB. I just ran a test with the latest master sources and the DB is there after power cycle, looking forward to this to be published on NPM so I can have my users upgrade their installs. Thanks again!

**Comment by LowPowerLab** [comment]
UPDATE: After a few hours with 1.4.2, it appears that node crashes. My other code that uses fs for file storage has not changed, but it's throwing these types of errors whenever my code is trying to write to a binary file: 

POST ERROR: EMFILE, too many open files '/home/pi/moteino/db/0030_GPM.bin'

So perhaps some file handle was left open in your code?

**Comment by louischatriot** [comment]
Thanks for letting me know. It looks exactly like the problem the latest commits are designed to solve (a return statement that was used for development and I had forgotten to remove). Basically it makes nedb keep all file descriptors, and after too many compactions the process can't open any more fds.

The commits should solve the issue, I think I'll also add a specific test for this behavior.

**Comment by LowPowerLab** [comment]
Several hours into the day, I see no open handles, and the app is not crashing. I think your last commit fix did the trick.

**Comment by louischatriot** [comment]
Indeed, and I also created a test specific for this. I published the full version as v1.5.0.

Thanks for your feedback !

**Comment by LowPowerLab** [comment]
Excellent work, thanks Luis!
