### ISSUE TITLE
How to search from a particular database?

### ISSUE THREAD

**Issue by pravin-d** [louischatriot/nedb#332]
Suppose I have more than one db "Users" and "Admin", how does db.find() work in this case ?

**Comment by lukasbestle** [comment]
So you want to search in multiple datastores (NeDB files) at the same time? Or what are you trying to achieve?

**Comment by pravin-d** [comment]
Yup..

**Comment by lukasbestle** [comment]
That does not work out of the box, as multiple datastores are multiple JavaScript objects. You can do the following though:

- Write a function that takes a datastore object, runs the search on it and returns a promise that gets the results after NeDB has found the data.
- Use `Promise.all` to call a function after both datastores have completed the find operation.
- Merge the results.

If you need any specific code, don't hesitate to ask.

**Comment by louischatriot** [comment]
Thanks, Lukas. Closing this as not a bug nor feature requesT.

**Comment by pravin-d** [comment]
Thank you.. I guess I got it. I was wondering if there was anyway to do it with in-built functions..
