### ISSUE TITLE
Error when trying to require browser version of NeDB

### ISSUE THREAD

**Issue by faelcorreia** [louischatriot/nedb#333]
I'm developing a node-webkit application and I want to use the browser version of NeDB.
Using gulp, I run browserify to create my `bundle.js`. The problem is when I try to import the browser version of NeDB I face an error about a require inside the `nedb.js` file.

Here is my require:

    var Nedb = require('nedb/browser-version/out/nedb')

The error:

    events.js:141
        throw er; // Unhandled 'error' event
        ^

    Error: Cannot find module './model' from 'E:\Rafael\Dev\situations\node_modules\nedb\browser-version\out'

Looking for model inside the nedb.js file, I saw that it tries to import using the current directory, but the file is in another one.

The require used by NeDB:

    var model = require('./model')

File structure:

    nedb
      browser-version
        out
          nedb.js
      lib
        model.js

Steps to reproduce the problem:

    browserify node_modules\nedb\browser-version\out\nedb.js -o test.js

    Error: Cannot find module './model' from '<project path>\node_modules\nedb\browser-version\out'

What am I missing about the NeDB browser version and browserify?

**Comment by louischatriot** [comment]
Well browserifying the browser version which is already the Node version browserified cannot yield good results :)
