### ISSUE TITLE
[question] [discussion] [help needed] Creating stubs for `nedb`

### ISSUE THREAD

**Issue by hellboy81** [louischatriot/nedb#335]
what is the best way to create stubs for `nedb`

In `SUT`  db instance is initialized as follows:

```js
var db          = new (require('nedb'))()
```

Possible solutions - both with `proxyquire`:

```js
var db = {
   remove: sandbox.stub(),
}

db.remove.yields(...)

proxyquire('...', {
   'nedb': function () { return db }
})
````

The second one - using `createStubInstance`:

```js
var Nedb = require('nedb')
var db = sinon.createStubInstance(Nedb)

db.remove.yields(null)

proxyquire('...', {
   'nedb': function () { return db }
})
```

Both solutions works4me.

Which solution should be used? Is there better solution?

**Comment by louischatriot** [comment]
I have no experience with sinon testing of nedb but I usually don't recommend mocking and stubs which are not a good way to test. Simply create a separate environment with a test database to test in real conditions.

**Comment by hellboy81** [comment]
> usually don't recommend mocking and stubs which are not a good way to test
why?

>Simply create a separate environment with a test database to test in real conditions.

and this tests are still unit tests?
