### ISSUE TITLE
why use not use simple localStorage, if nedb is only using storage as a dumb savestate?

### ISSUE THREAD

**Issue by kaizhu256** [louischatriot/nedb#336]
the browser version, nedb.min.js has grown from ~70kb to ~100kb with the extra localforage crud (since commit 0b564ba6743f940357cd3531b64e39e815524660)

i'm going over the source code, and don't seem to see any need for indexeddb or websql, and likely there will never b a need in the forseeable future, if u want to keep it cross-compatible with nodejs.

**Comment by louischatriot** [comment]
Well there is a need even if you don't see it :) It has no impact with cross-compatibility with Node.js, but increases drastically available storage space on the browser.

**Comment by kaizhu256** [comment]
oh, ic.  just verified localstorage is limited to ~5million characters.  i kno i'm nagging, but hope u'll keep the design simple and lightweight : )

my use-case for nedb is datastore for a virtual emulation of elasticsearch in the browser, so i can run kibana as a serverless app.

**Comment by kaizhu256** [comment]
just fyi, https://kaizhu256.github.io/node-swagger-lite/build..beta..travis-ci.org/app/index.html#!/_test/crudUpsertOne

created a persistent swagger-ui api server that can either
1. run entirely in-browser (using browser nedb datastore), or
2. on a real server (using nodejs nedb datastore)

next step is to emulated elasticsearch api in-browser, and then integrate it with kibana - serverless kibana app!

![screen shot 2016-01-11 at 17 32 54](https://cloud.githubusercontent.com/assets/280571/12230799/d37ae850-b88d-11e5-9f7c-8fa8edaa4471.png)
