### ISSUE TITLE
Sometimes db freezes.

### ISSUE THREAD

**Issue by sanket-mindstix** [louischatriot/nedb#337]
In my application I am contentiously doing db insert/read/update/delete and also db compression operations too frequently. At one situation(very rare) all my db API's are failing to perform db operations i.e only call is made for accessing db but api's didn't get any response from db. So my whole app's working gets stopped at that point. Can you please look into this issue. Where can I see db logs to troubleshoot this issue? Please check into this issue. Thanks

**Comment by louischatriot** [comment]
Please follow the bug reporting guidelines when reporting a bug: https://github.com/louischatriot/nedb#bug-reporting-guidelines

I'll close this in the meantime.

**Comment by sanket-mindstix** [comment]
Please tell me where can I see all db logs?

On Tue, Dec 15, 2015 at 1:05 PM, Louis Chatriot <notifications@github.com>
wrote:

> Please follow the bug reporting guidelines when reporting a bug:
> https://github.com/louischatriot/nedb#bug-reporting-guidelines
>
> I'll close this in the meantime.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/louischatriot/nedb/issues/337#issuecomment-164673720>.
>



-- 
Sanket Kulkarni.
Mindstix Software Labs
http://www.mindstix.com

Email: *sanket.kulkarni@mindstix.com <baljeet.singh@mindstix.com>*
Phone: +91 7276007159
Skype: sanket.kulkarni4

**Comment by louischatriot** [comment]
There are no db logs.

**Comment by sanket-mindstix** [comment]
Thanks

**Comment by sanket-mindstix** [comment]
Are there any config file or flag referred by db during performing db operation?
