### ISSUE TITLE
Find fails silently when loadDatabase can't access data file

### ISSUE THREAD

**Issue by ziacik** [louischatriot/nedb#339]
Steps to reproduce:
1. Create a test.db
2. `sudo chown root:root test.db`
3. `node load.js` (see below)

```
var db = new (require('nedb'))('test.db');
db.loadDatabase(function(err) {
        console.log('load error', err);
});
db.find({}).exec(function(err, res) {
        console.log('find error', err);
        console.log(res);
});
```

Now while "load error" is shown (though actually it's a write error), the "find error" is never shown because the callback is never called. Of course, the database is in invalid state due to the loading error, still I think the callback in `exec` should be executed. The error could be something like 'database in wrong state'.

**Comment by louischatriot** [comment]
Actually that's not the case, as the find didn't fail, it was simply never executed because the loadDatabase failed. It has been queued in the executor though and will be executed upon a successful loadDatabase.

I've updated the readme to reflect this non trivial behavior.
