### ISSUE TITLE
Database records deleted sometimes

### ISSUE THREAD

**Issue by vishvas29** [louischatriot/nedb#340]
Hello,

I have used nedb in Raspberry Pi. Sometimes all records of DB are deleted by itself. I don't know how it can be possible? Can you help me here?

**Comment by louischatriot** [comment]
You msut be using a version prior to v1.5, please try upgrading to the latest version which fixed this sort of behavior (caused usually by the user unplugging the RPi shortly after a launch or autocompaction).
