### ISSUE TITLE
Promise support

### ISSUE THREAD

**Issue by stanonyime** [louischatriot/nedb#344]
Does Nedb support Promises?

**Comment by lukasbestle** [comment]
It doesn't *return* promises, but you can wrap your callback in a promise function, there's nothing that could go wrong on NeDB's end (it just doesn't care).

**Comment by stanonyime** [comment]
It would be nice if NeDB returned a promise natively. Like Mongoose, it would assume that a promise is expected if callback is omitted.

**Comment by lukasbestle** [comment]
I agree, that would be a nice feature.

**Comment by JamesMGreene** [comment]
A light :+1: for me.

**Comment by JamesMGreene** [comment]
> It would be nice if NeDB returned a promise natively. Like Mongoose, it would assume that a promise is expected if callback is omitted.

A light :+1: for me.

**Comment by ruffrey** [comment]
Would you accept a pull request for this feature?

**Comment by louischatriot** [comment]
I don't think this feature is a priority, and unfortunately my bandwidth will become extremely limited starting next week so even reviewing PRs will be tough.

**Comment by hyzhak** [comment]
mast have features especially with new async/await for ES7

**Comment by jampy** [comment]
Have a look at [nedb-promise](https://www.npmjs.com/package/nedb-promise)

**Comment by wayofthefuture** [comment]
Do you know if the nedb-promise mimics standard promise architecture? In their docs they seem to use "await" for everything.

**Comment by wayofthefuture** [comment]
What about this? (it's a variant of nedb-promise)

```javascript
        this.db = new Nedb();
        let methods = ['insert', 'count', 'update', 'remove', 'ensureIndex', 'removeIndex'];      //'find', 'findOne' necessary ??? 

        Object.keys(methods).forEach((meth) => {
            this[meth] = thenify(meth.bind(this.db));
        });

        this.find = function (query, projection) {
            let cursor = this.db.find(query, projection);
            cursor.exec = thenify(cursor.exec.bind(cursor));
            return cursor;
        };
        this.findOne = function (query, projection) {
            let cursor = this.db.findOne(query, projection);
            cursor.exec = thenify(cursor.exec.bind(cursor));
            return cursor;
        };
```
