### ISSUE TITLE
Support MongoDB TTL feature

### ISSUE THREAD

**Issue by JamesMGreene** [louischatriot/nedb#346]
It would be awesome if NeDB supported a Time-To-Live (TTL) feature for expiring documents per datastore.

MongoDB has implemented this feature via a special indexing property:
    https://docs.mongodb.org/manual/tutorial/expire-data/

**Comment by louischatriot** [comment]
Nice feature indeed, actually it would have been useful to another project of mine a few weeks ago :) But to be honest I'm very unlikely to find the time to do it, it is not trivial to do it properly (managing restarts and so on). Will notify if I do it !

**Comment by JamesMGreene** [comment]
I was actually working on a PR to offer up for it.  :stuck_out_tongue:

**Comment by louischatriot** [comment]
Nice :) in that case I'll happily review.

**Comment by JamesMGreene** [comment]
@louischatriot: Please consider reopening this issue until the corresponding PR #349 is merged or rejected. Thanks!
