### ISSUE TITLE
Exact (deep) match array

### ISSUE THREAD

**Issue by jmversteeg** [louischatriot/nedb#348]
There seems to be no way to exactly match an array.

```js

'use strict';

const pify      = require('pify');
const Datastore = require('nedb');

const d = new Datastore();

const insert = pify(d.insert.bind(d));
const find   = pify(d.find.bind(d));

insert({'foo': ['bar', 'baz']})
    .then(() => find({'foo': ['bar', 'baz']}))
    .then(console.log);

```

This will not return any documents (which is inconsistent with the behaviour of MongoDB) 

The best approximation right now would be

```js

insert({'foo': ['bar', 'baz']})
    .then(() => find({$and: [
        {'foo': 'bar'},
        {'foo': 'baz'},
        {'foo': {$size: 2}}
    ]}))
    .then(console.log);

```

But this does not perform an exact match (e.g. documents where `foo` equals `['baz', 'bar']` would also be returned).

**Comment by louischatriot** [comment]
If submitting what you think is a bug, please follow the bug reporting guidelines (see end of readme).

In that specific case it's a non-existing feature, as nedb is not 100% on par with MongoDB for obvious reasons. I'm not planning on adding it but I can review a PR.
