### ISSUE TITLE
Watch the file for changes

### ISSUE THREAD

**Issue by IonicaBizau** [louischatriot/nedb#353]
Having the following piece of code:

```js
var Datastore = require('nedb')
  , db = new Datastore({ filename: 'foo', autoload: true })
  ;

db.insert({ "hi": "foo" }, function (err, data) {
    console.log(err || data);
});

setInterval(function () {
    db.find({}, function (err, data) {
        console.log(err || data);
    });
}, 1000);
```

Each second, I output the items.

If I do `echo '{"test": "bar","_id": "someid"} >> foo'` I expect the items count to be changed. Currently this doesn't happen.

Would be handy to have a feature for watching the file for changes.

**Comment by louischatriot** [comment]
That's not an expected -nor desirable- behavior. The datafile must be touched by nedb and nedb only, the serialization process is more complicated than it appears. If you need to use nedb with multiple processes you need to put it in a separate process and create an API wrapper around it, a la MongoDB. There was a project on this but never finished it seems, and in my opinion if you need that, you need MongoDB.

**Comment by IonicaBizau** [comment]
> The datafile must be touched by nedb and nedb only, the serialization process is more complicated than it appears. 

My case is that I want to keep these documents in a file but I want to be able to `git pull` anytime I want and if the file is changed I want to reload that somehow. Is there a way to reload the file anyway? Then I will just take care of watching and reloading.

Thanks! :cake:

**Comment by lukasbestle** [comment]
You should be able to call `datastore.loadDatabase(callback)` again. I have not tested if that breaks something though.

**Comment by louischatriot** [comment]
Calling loadDatabase again will update the database to match the datafile. The recommended way though is to simply restart your Node server.

**Comment by IonicaBizau** [comment]
@louischatriot Is there any downside of calling `loadDatabase`?

**Comment by louischatriot** [comment]
No downside as long as you call it from your process, not another process, which is why restarting the Node app is usually a better way to go.

**Comment by IonicaBizau** [comment]
Thanks, guys! :+1:  And thanks for the nice module! :sparkles:
