### ISSUE TITLE
Sorting International Characters

### ISSUE THREAD

**Issue by SeanConnelly** [louischatriot/nedb#354]
If I sort on a string field that contains international characters, then I currently get this sort order...

Ana Trujillo Emparedados y helados
B's Beverages
Berguvsvägen  8
Blauer See Delikatessen
Blondel père et fils
Bon app'
Bottom-Dollar Markets
Bólido Comidas preparadas      <--This is not in the right sort position
Cactus Comidas para llevar

It looks like this code is doing the sort comparison...

function compareNSB (a, b) {
  if (a < b) { return -1; }
  if (a > b) { return 1; }
  return 0;
}

JavaScript string comparisons will compare the unicode values and will not be aware of how the encodings should be ordered for readers.

There is a built in JavaScript function that will do this correctly...

function compareNSBforInternationalStrings (a, b) {
  return a.localeCompare(b)
}

It will return -1,1,0 as per the original code.

I came across this whilst developing a browser model proxy solution that can use NeDB as the backend storage solution. I have over 10K of unit tests that are using data from the Northwind data, which I save into NeDB.

I was then unit testing that a local sort would match a server side NeDB sort which is how I spotted the above issue.

If your still not sure, take a look at this site (its not mine)...

http://bigprof.com/demo/orders_view.php

Click on the Customer column to order the customers, and then go to page 8 on the grid. You will see that 

Bólido Comidas preparadas

comes before

Bon app'

I would suspect the above site is a SQL driven solution and the sort order would be typical of a SQL sort order.

I've attached an NeDB database file containing all of the orders from the Northwind data. If you sort on ShipName then you will see the problem.

Kind Regards,
Sean

[Orders.zip](https://github.com/louischatriot/nedb/files/85699/Orders.zip)

**Comment by louischatriot** [comment]
Indeed, good remark. As of nedb v1.6.1 you can specify your own string comparison function as an argument to nedb (see https://github.com/louischatriot/nedb#creatingloading-a-database). You can use this with `localeCompare` and your specific locale.
