### ISSUE TITLE
upsert always inserting

### ISSUE THREAD

**Issue by adammeyer** [louischatriot/nedb#367]
I'm not sure if this is an issue or if I'm performing the update incorrectly.  What I want to do is update a record and insert it if it doesn't exist.

Here is my update statement.  I put it in a loop.
```javascript
i  = {
  id: 1,
  data: 'hello'
};
db.update({id: i.id}, i, { upsert: true });
```

The result is all of the records are inserted.
![image](https://cloud.githubusercontent.com/assets/4603906/12723398/5900d7ec-c8d7-11e5-97e6-dd99216f7715.png)

**Comment by louischatriot** [comment]
Please follow bug reporting guidelines when reporting a bug. For this one, please read the readme :)

**Comment by bdfoster** [comment]
Looks correct... I think you're misunderstanding how nedb works. Try
db.find() and search for all records with 'id' equal to 1. I bet you'll
find there's only one record.

As a side note, 'id' is most certainly not the same as '_id', which is the
unique key in the file store.

But yea, read the README.

**Comment by zevero** [comment]
Just restart your node app and you will see that autocompaction will take
care to remove all unneeded entries.

2016-02-01 18:24 GMT+01:00 Brian Foster <notifications@github.com>:

> Looks correct... I think you're misunderstanding how nedb works. Try
> db.find() and search for all records with 'id' equal to 1. I bet you'll
> find there's only one record.
>
> As a side note, 'id' is most certainly not the same as '_id', which is the
> unique key in the file store.
>
> But yea, read the README.

**Comment by adammeyer** [comment]
Thanks @zevero, that was it!
