### ISSUE TITLE
How do you remove everything from a collection?

### ISSUE THREAD

**Issue by JoshTerAvest** [louischatriot/nedb#370]
I can't seem to find a way to empty a collection. How do I remove a collection's contents so I can add new things to it without conflict.

**Comment by lukasbestle** [comment]
One database equals one collection. Clearing everything would be:

```
db.remove({}, { multi: true }, function (err, numRemoved) {
  
});
```

**Comment by JoshTerAvest** [comment]
Not sure how I missed that in the docs. Thanks!

**Comment by matteocontrini** [comment]
I'd suggest closing this issue ;)

**Comment by louischatriot** [comment]
Right
