### ISSUE TITLE
createdAt property removed when updating document

### ISSUE THREAD

**Issue by astrilchuk** [louischatriot/nedb#371]
Updating a document causes an existing createdAt property (with timestampData true) to be excluded from the updated document.  I would expect the original createdAt value to be included with the updated document.

https://gist.github.com/astrilchuk/3d9ef86d5955735f1e30

**Comment by louischatriot** [comment]
Thanks for the nice bug report. In your case there is no bug in nedb, the query you supply is a whole new document, not a modificating query, which is why the document simply gets replaced, wiping out all properties including `createdAt`.

**Comment by astrilchuk** [comment]
Even if the new document replaces the old, shouldn't the new document get it's own createdAt property?  What if I want to update documents and have an expireAfterSeconds index on the createdAt property?  Some documents will expire, others will never expire.

Just a thought, thanks for the great project.

**Comment by louischatriot** [comment]
Hmm it seems that you are indeed right on this one. I'll need to give it some more thought but that seems like a very valid comment. I still don't know what date to use in that case, the original one or the current one. I think the original one makes more sense, but need to check the MongoDB docs. Do you have an opinion on this?

**Comment by astrilchuk** [comment]
I think the new document should inherit the createdAt value of the original document since it is an 'update' that been requested.  Having said that, I'm fairly new to these document stores so I may be incorrect.

**Comment by kaizhu256** [comment]
here's real-world example of bug implementing nedb as datastore for the swagger petstore example @
https://kaizhu256.github.io/node-swagger-lite/build..alpha..travis-ci.org/app/index.html#!/store/placeOrder

i use db.update(..., { upsert: true }) for POST request, and the second time i POST, the createdAt is missing. i think using the original createdAt timestamp also makes more sense.  the user can always override createdAt with the current timestamp if he so chooses.

![screen shot 2016-02-14 at 16 39 58](https://cloud.githubusercontent.com/assets/280571/13032760/28c32a36-d33a-11e5-94fe-d2b7cded3517.png)

**Comment by kaizhu256** [comment]
my current workaround is to explicitly set createdAt to current time as shown below.  i don't mind using current-time in this particular case because its a 'replace' (update using $set seems to preserve createdAt original time)

```
                    case 'crudCreateOrReplaceOne':
                    case 'crudCreateOrReplaceOneByKeyUnique':
                    case 'crudCreateOrUpdateOne':
                    case 'crudCreateOrUpdateOneByKeyUnique':
                        crud.data.body = crud.data.body || local.utility2.jsonCopy(crud.data);
                        delete crud.data.body.id;
                        delete crud.data.body[crud.keyUnique];
                        crud.data.body[crud.keyAlias] = crud.data[crud.keyUnique];
                        // replace doc
                        if (crud.operationId.indexOf('Replace') >= 0) {
                            crud.data.body.createdAt = new Date().toISOString(); // workaround for createdAt
                            crud.collection.update(
                                crud.queryByKeyUnique,
                                crud.data.body,
                                { returnUpdatedDocs: true, upsert: true },
                                onNext
                            );
                        // update doc
                        } else {
                            crud.collection.update(
                                crud.queryByKeyUnique,
                                { $set: crud.data.body },
                                { returnUpdatedDocs: true, upsert: true },
                                onNext
                            );
                        }
                        break;
```

**Comment by louischatriot** [comment]
I fixed this by keeping the original `createdAt` when an update results in a full replacement. This is now part of v1.8 (warning: there is a minor breaking change in the update callback signature documented in the readme and change log).

**Comment by astrilchuk** [comment]
That's great Louis, thanks!
