### ISSUE TITLE
Inconsistent type returned from update

### ISSUE THREAD

**Issue by astrilchuk** [louischatriot/nedb#374]
When updating with upsert:true and returnUpdatedDocs:true (and multi implied false), the object returned is inconsistent.  If the operation becomes an insert, the returned doc is the document.  If the operation is an update, the document is wrapped in an array.

I believe with multi:false the returned doc should not be wrapped in an array.  If the array is the preferred return type, then I feel it should be consistent regardless if the operation is an insert or update.

https://gist.github.com/astrilchuk/866d62a32607df190198

**Comment by louischatriot** [comment]
Indeed the update callback signature was not coherent and not very clean. I modified it accordingly and documented the change in the readme. This breaks compatibility with NeDB v1.7.4 and prior, code relying on this should be updated (not too hard though!).
