### ISSUE TITLE
$elemMatch (projection)

### ISSUE THREAD

**Issue by Bobozee** [louischatriot/nedb#375]
First, thank you for the great tool. 

This is not an issue but a question.

Currently NeDB delivers all items of array field. Is it possible to fetch specific item by providing query with projection object using $elemMatch like MongoDB does?

https://docs.mongodb.org/manual/reference/operator/projection/elemMatch/

Thank you.

**Comment by marshallswain** [comment]
I'm not sure if this will help your exact situation, but I remembered seeing this a little while ago: 
https://github.com/louischatriot/nedb/pull/364

**Comment by Bobozee** [comment]
$elemMatch if working fine for queuing documents but does not work as projection. What I need is selecting specified by query in projection phase array element:

`{
doc: "A",
items: [
   {name: "Item1", color: "green"},
   {name: "Item2", color: "red"}
]
}`

`collection.find({doc: "A"}, {$elemMatch: {'items.color': 'red'}}, (err, docs) => {
   // returns:
   // {doc: "A", "items": [{name: "Item2", color: "red"}]}
});`

**Comment by louischatriot** [comment]
Indeed the $elemMatch operator is not implemented as a projection so you would need to do so manually.
