### ISSUE TITLE
Database file is changed when db.loadDatabase() is called

### ISSUE THREAD

**Issue by onion-soup** [louischatriot/nedb#377]
I have a db file (~1.5MB).
After I call `db.loadDatabase('mydb.db')` some entries in the file get shuffled.
Is it a known issue? How can I fix that?

**Comment by lukasbestle** [comment]
`loadDatabase` loads the documents (database entries) into memory line by line and builds a collection of the documents. After that, it saves a cleaned version (without deleted or old representations) back to the file. You can read more about this in the README.

If you believe that what happens to you is a bug, please follow the [bug reporting guidelines](https://github.com/louischatriot/nedb#bug-reporting-guidelines).

**Comment by onion-soup** [comment]
Thanks for clarification. 
May I rephrase my question: is it expected that order of lines in the file can change after `loadDatabase`? I am not sure if it's a bug or not.

**Comment by lukasbestle** [comment]
Yes, sure. If you create one document and update it, your DB will contain two lines. After loading again, one line will remain with the updated information. If you then delete it, the DB will again contain two lines. After loading, the file will be empty.

So that the contents change when loading is totally normal.

**Comment by onion-soup** [comment]
Does it mean that I should call `loadDatabase` before exiting my process to ensure that next time I call `loadDatabase`, the file will not be altered? So that I don't have unnecessary diffs before doing `git commit`

**Comment by lukasbestle** [comment]
If you have your NeDB database in version control, that would make sense. NeDB uses an append-only format, which will look quite messy in your Git history if not cleaned up by `loadDatabase`.

**Comment by onion-soup** [comment]
Alright. thanks
