### ISSUE TITLE
Option for setting _id size

### ISSUE THREAD

**Issue by lauritzsh** [louischatriot/nedb#380]
Hi, great library, makes it easy to getting started on a new project. I was wondering if it could be possible to allow users to set the size of `_id` themselves? I do not really need a 16 length id, just four to six characters would be more than enough combinations and easy to remember still.

I can see it is currently hardcoded, I don't know if there are some "options" object being passed around where id size could be set.

**Comment by lukasbestle** [comment]
Why do you need to remember the ID? It is meant as an internal ID to make sure that changes are applied to the correct document. If you need your own shorter ID for something, you should add your own field and use that.

**Comment by lauritzsh** [comment]
I'm using the id to associate it with an uploaded file, so www.example.com/7yfa (if `_id` was four characters) would find the file and display it. Is this a wrong use of `_id` and what do you suggest instead then?

**Comment by lukasbestle** [comment]
Ah, that makes sense. You can [set your own ID when creating documents](https://github.com/louischatriot/nedb#inserting-documents), but **you need to make sure yourself that is not already in use**. NeDB uses [its own uid function](https://github.com/louischatriot/nedb/blob/master/lib/customUtils.js#L12) which you can use by loading that file in your application, but how the UID looks like does not matter as long as it is unique.

**Comment by lauritzsh** [comment]
That's possible but I just mean the logic is already there https://github.com/louischatriot/nedb/blob/cadf4ef434e517e47c4e9ca1db5b89e892ff5981/lib/datastore.js#L363-L370 I thought it might just be easier to have the function take a `len` parameter and default to 16.

How would I make sure the id I generate myself is not in use? I can think of doing a `findOne` and check the id but this seems convoluted.

**Comment by louischatriot** [comment]
Hey,
@lukasbestle solution is the best one (create another field to store that information). Usually I'm not in favor of setting the `_id` field, even if that's possible. The only cases where I do it are for foreign keys between two collections in 1 to 1 relationships, since you do know that the _ids are unique.

I'll close this.
