### ISSUE TITLE
Inconsistency between mac and windows, write and read operations fail silently

### ISSUE THREAD

**Issue by giuge** [louischatriot/nedb#386]
I'm using neDB in an electron application to store a user media library (~2k images/videos stored as base64). While everything works flawlessly on mac I'm running into issues on windows.

The database file gets created but 8/10 of the time no write/read operations get done. Sometimes it works and I was able to see that the library has been written successfully to the database and was read as well. Unfortunately, no error gets logged in the console.

That's what I do:

```js
import _ from 'lodash'
import alt from './../lib/alt'
import Datastore from 'nedb'

const db = new Datastore({ filename: `${USER_DATA}/library.db`, autoload: true})

loadLibrary() {
    return ((dispatch) => {
      db.find({}, (err, library) => {
        if(err) console.log(err)
        else dispatch(_.orderBy(library, 'sortDate', 'desc'))
      })
    })
  }

saveAfterImport(importedMedia) {
    // Imported media is 2k images with base64 thumb and various info
    return ((dispatch) => {
      db.insert(importedMedia, (err, media) => {
        if(err) console.log(err)
        else dispatch(_.orderBy(media, 'sortDate', 'desc'))
      })
    })
  }
```

I'm a bit lost on how to spot the issue and any advice would be highly appreciated. I even tried with a smaller library made of only 18 pictures, but it still fails to write read. 

Here's an example library containing 2 elements, the base64 string has been truncated: https://gist.github.com/giuge/edc61624d5b2e960f87a

**Comment by louischatriot** [comment]
Hello, please follow the bug reporting guidelines in the readme. I'll reopen when you resubmit.
