### ISSUE TITLE
Over 256Mb datafile throw err upon opening

### ISSUE THREAD

**Issue by ornic** [louischatriot/nedb#389]
Windows x64 Node v5.3.0 and v5.7.0 x64

Datafile contains large portions of data (about 1 Mb for each JSON) updated continuosly. Clean datafile (no deleted entries) has size about 3 Mb.

It is looks like somebody (NEDB?) try to load all file into one string and bumps into https://github.com/nodejs/node/issues/3175 256Mb limit.

May be it will help to set some size limit to force compactification?

Node window (VS 2015 community)
```
...\src\node_modules\nedb\lib\datastore.js:77
    if (err) { throw err; }
               ^

Error: toString failed
    at Buffer.toString (buffer.js:397:11)
    at tryToString (fs.js:410:15)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
```

Interactive node
```js
> var Datastore = require('nedb'),
.     db = new Datastore({ filename: './DB/DBSMdata.nedb', timestampData: true, autoload: false });
undefined
> db.persistence.compactDatafile()
undefined
> db.loadDatabase(function (err) {    // Callback is optional
.     console.log(err)
. });
undefined
[Error: toString failed]
```

**Comment by lukasbestle** [comment]
See #363. NeDB is not meant to be used with that large databases. You should probably use MongoDB.

**Comment by ornic** [comment]
Thanks, @lukasbestle, I searched with wrong words.

The DB is not that large (3 Mb of actual data), but I messed up auto compactification and got stuck with huge file I had to edit in UltraEdit32 to restore NEDB ability to work. :) Now that I know, I will add some more checks for size.

But mention something about 256Mb limit of DB filesize in https://github.com/louischatriot/nedb#persistence may be useful for future dummies like me.

**Comment by lukasbestle** [comment]
Ah, alright. If auto-compaction works for you now, that should be solved. The note in the README is a good idea however. @louischatriot?

**Comment by louischatriot** [comment]
Hmm adding a check on file size could be an idea but there are a lot of questions here. I'm pretty sure that there is no 256 MB limite on nedb datafiles though, that must be something to do with your system.

**Comment by ornic** [comment]
As I can see (but I am pretty much newbie in Node) there is a problem in Buffer.js during DB loading and trying to convert all file from Buffer to String in one go. Since one String can't be longer than kMaxLength in V8.

**Comment by louischatriot** [comment]
Final comment on this: if this is indeed an issue that's reproducible, please create a test case according to the bug reporting guidelines, which I will then review!

**Comment by ornic** [comment]
Sorry, I am new to these guidlines, and if I'm wrong please point me to the proper doc.

I tested in Express. Folder for DB file is `./DB`

**app.js**
```js
var express = require('express');
var http = require('http');
var app = express();

app.set('port', process.env.PORT || 3000);
app.set('views', './views');
app.use(express.logger('dev'));
app.use(express.json());
app.use(express.urlencoded());
app.use(express.methodOverride());
app.use(express.static('./public'));

var stats = require('./routes/index.js');
app.get('/testDB', stats.testDB);

http.createServer(app).listen(app.get('port'), function () {
    // console.dir(process.versions);
    console.log('Express server in mode ' + app.get('env') + ' listening on port ' + app.get('port'));
});
```
**index.js.**
```js
function checkDBsize() {
    var fs = require('fs');
    
    fstat = fs.statSync('./DB/DBtest.nedb');
    var filesize = fstat["size"];

    console.log("DB size is", filesize, "bytes");

    return filesize;
}

function increaseDBsize(db, limit, res) {
    
    var data = [];
    for (var i = 0; i < 15; i++)
        data.push({index: i, dataSegment: JSON.stringify(data)});
    
    db.insert({ test: true, dataChunk: data }, function (err, newDoc) {
        if (newDoc) {
            db.remove({ test: true }, { multi: true }, function (err, recNum) {
                if (err) {
                    console.log("error deleting", JSON.stringify(err));
                } else {
                    filesize = checkDBsize();
                    if (filesize >= limit)
                        res.send(filesize + " bytes");
                    else
                        return increaseDBsize(db, limit, res);
                }
            });
        } else {
            console.log("error adding", JSON.stringify(err));
        }
    });
}

exports.testDB = function (req, res) {
    
    var text2send = "";
    var filesize = 0;
    var DatastoreTest = require('nedb'),
        db = new DatastoreTest({ filename: './DB/DBtest.nedb', timestampData: true, autoload: true });
    
    filesize = increaseDBsize(db, 350000000, res); // With 250 all is OK.

}
```

First run of http://localhost:1337 (I'm using VS2015 community and NODE 5.7.0) produces NEDB database file ~335Mb.

console output is:
```
DB size is 43849712 bytes
DB size is 87699424 bytes
DB size is 131549136 bytes
DB size is 175398848 bytes
DB size is 219248560 bytes
DB size is 263098272 bytes
DB size is 306947984 bytes
DB size is 350797696 bytes
GET /testDB 200 9252ms - 15b
```

Second run crashes Node.
```
C:\Users\Roman\Documents\Git\dbsm\src\node_modules\nedb\lib\datastore.js:77
    if (err) { throw err; }
               ^

Error: toString failed
    at Buffer.toString (buffer.js:397:11)
    at tryToString (fs.js:410:15)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:401:12)
 Press any key to continue...
```

**Comment by louischatriot** [comment]
Sorry but this still doesn't adhere to the bug reporting guidelines, see bottom of the readme. Specifically, please remove all unneeded dependencies such as Express to remove external factors, and you sohuld be able to make it so the crash/bad assertion occurs in only one run.

**Comment by PetrChalov** [comment]
When you try to open NeDb size of 500MB, an exception is thrown.

/```
node_modules/nedb/lib/datastore.js:77
     if (err) {throw err; }
                ^

Error: toString failed
     at Buffer.toString (buffer.js: 397: 11)
     at tryToString (fs.js: 410: 15)
     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js: 401: 12)

```
Probably due to the fact that the file size exceeds the maximum Buffer if you are going to deal with this bug.

Thank you.

**Comment by markgeraty** [comment]
Here is a [gist](https://gist.github.com/markgeraty/4b5cd938e6a54aa292b2364348c0c668) of @ornic's code, simplified down.

Are there any plans to accommodate larger file sizes?  Or should people be using https://github.com/Ivshti/linvodb3 or mongo instead?

If not, I do agree with some of the previous posters that this should be addressed clearly near the top of the README.

**Comment by anthonyettinger** [comment]
I'm also seeing this error on db size of 256MB.

**Comment by jampy** [comment]
Seems that the reason is the max string size supported by Chrome, which is 512MB/2: http://stackoverflow.com/q/34957890

**Comment by chovy** [comment]
Can we remove the limit if you're using nedb from node.js on the server? There is no need for a 256MB database limit.

**Comment by lukasbestle** [comment]
This is not a limit that has been hardcoded into NeDB. It's a limitation of how many characters can be loaded into the string in Node.

NeDB could load the DB by streaming from the file, but this wouldn't solve the issue that large DBs won't perform well. Consider using a "real" DB like MongoDB.

**Comment by JamesMGreene** [comment]
To be more clearly linked, we believe this would fix:
 - #363
 - #389
