### ISSUE TITLE
Reading database in a loop while something is being added to it

### ISSUE THREAD

**Issue by davidhq** [louischatriot/nedb#394]
Is this the use case where this should work?

I had bigg issues and after switching to mongoose and mongo, this didn't happen in the exact same code.

So basically I had one autoloaded database on disk and I was reading it from one script every 2s while another script was putting objects into the collection... the first script never saw the new items until after I restarted it, then they showed... but not the further ones being added, for this another restart was required and so on...

Is this a bug or just the design consequence?

Apart from this I was seeing things like:

`Error: ENOENT: no such file or directory, rename './repositories/data/accounts.db~' -> './repositories/data/accounts.db'`

which doesn't make much sense to me at all.

I expected this lib to be more robust, maybe I'm doing something wrong, not sure.. I'd still like to have one good option for file databases and the feature that api is a subset of mongo is very cool.

**Comment by Bobozee** [comment]
There is no such "close database" function in nedb yet and the storage 
file may stay exclusively open while the other process tries to read 
from. This may cause the failure you've described.

**Comment by olympum** [comment]
What's the recommended approach to avoid this? I have cron jobs and users calling the same app with NeDB, and I am seeing this error all the time.

**Comment by lukasbestle** [comment]
A database that should be accessible from multiple processes always needs a central process that manages the database. Embedded databases like NeDB don't have that because they are, well, embedded, so they shouldn't be used by multiple processes at the same time.

Recommended approach: Don't use NeDB, use a proper database like Mongo.

**Comment by louischatriot** [comment]
To confirm what @lukasbestle said: if you need multi client access to a database, there are high chances you need a full blown database such as Mongo. If you really want to do that with NeDB you need to wrap it in an HTTP server that will run in a standalone process (much like what MongoDB does to expose its API), but again that probably just means your project has outgrown NeDB.
