### ISSUE TITLE
regex for string 'is' fails

### ISSUE THREAD

**Issue by Artem-Schander** [louischatriot/nedb#397]
Let's say I have two entries. `Louis Armstrong` , `Miles Davis` and `Ella Fitzgerald`. If I decide to look for `is` with the regex query, I'm getting no results.

The real world example is much more complex (multiple positive lookeheads), but the issue is the same. Every other string that i have tested worked well.

Here is my `query` variable:
```
let query = {
  name: {$regex: new RegExp('is', 'i')},
}; 
```

**Comment by louischatriot** [comment]
Please follow the bug reporting guidelines when reporting a bug.

**Comment by Artem-Schander** [comment]
Ok, i'll do so. Sorry for bothering you at this point :)
