### ISSUE TITLE
atomic update + insert?

### ISSUE THREAD

**Issue by dlmanning** [louischatriot/nedb#398]
I've been trying to figure out how to orchestrate an atomic update + insert. My situation is that I'm adding a bunch of documents, while also updating a reference in an existing document to include the new documents.

My concern, naturally, is that the inserts could fail independently of the update, leaving me with an invalid database.

My best idea so far is to first retrieve the to-be-updated document, modify it, and upsert the entire set of changes at once. Is there a better way?

**Comment by kaizhu256** [comment]
this should do the trick

```
                    case 'crudCreateOrUpdateOneById':
                        // create or update collectDoc
                        crud.collection.update(
                            { _id: 'asfoiifuSFfdk' },
                            { $set: {
                                field1: 'create or update field1',
                                field2: 'create or update field2',
                            } },
                            { returnUpdatedDocs: true, upsert: true  },
                            onNext
                        );
                        break;
```

**Comment by louischatriot** [comment]
@dlmanning unfortunately there is no way to guarantee atomicity or use transactions with NeDB, and I am not planning on adding that. For the vast majority of projects using NeDB this is not an issue but if this is crucial to your project I suggest you use a full-blown DB such as Mongo or Postgre
