### ISSUE TITLE
loadDatabase

### ISSUE THREAD

**Issue by simon-p-r** [louischatriot/nedb#401]
Hi

I am having a problem with this line throwing

https://github.com/louischatriot/nedb/blob/master/lib/persistence.js#L32

Can error be returned to loadDatabase function?  Currently I have to wrap creating a new Db function in a try catch.  What errors are propagated to loadDatabase methods?

Thanks
Simon

**Comment by CodeMan99** [comment]
That looks like an intentional breakage. Remove the "~" from the end of your filename.

If you can't do that, explain why, otherwise the author has reason to leave that intentional breakage there.

**Comment by bdfoster** [comment]
That's an intentional breakage, for sure.

I can't remember exactly what it is, but you're not closing or opening your
database correctly. A filename with a ~ at the end is a open filestore I
believe.

**Comment by simon-p-r** [comment]
Yes I understand that, I am asking for the error to be returned to handler rather than thrown. Also I cannot see what errors are returned to loadDatabase method currently which was part of my question. The fact nedb has no close method is also a concern.

**Comment by louischatriot** [comment]
Using a ~ is indeed considered an "intentional breakage" which is why it is thrown by the constructor directly, even before you can call loadDatabase. There are no plans to switch that check to `loadDatabase` since I don't see in what scenario you cannot know in advance the name of the datafile or at least it's format.

Concerning close, it is not needed as NeDB lives in the Node process and automatically gets closed (i.e. all file descriptors are released) when the process exits.

**Comment by simon-p-r** [comment]
I was using it to force error when testing as I could not generate the error returned by loadDatabase method.  What errors are returned by this method?

**Comment by CodeMan99** [comment]
@simon-p-r [code here](https://github.com/louischatriot/nedb/blob/150a4b18237803272704e9b568111e6f54a13f5b/lib/persistence.js#L275).

Possible errors:

 1. Directory creation failure.
 2. Key restraint check failure.
 3. Cannot read file do to permissions failure.
 4. Data corruption threshold.
 5. Indexing failure.

I don't really understand why you are "force error testing", so I don't think I can help beyond that.

**Comment by simon-p-r** [comment]
Thanks for the pointer @CodeMan99  I will see if I can catch any of them.  You need to be able to force errors so that calling code can handle the condition.

**Comment by CodeMan99** [comment]
@simon-p-r They should all be actual stack traces. You can `console.error(err.stack || err);` to be safe.
