### ISSUE TITLE
How to update _id once the entry is updated to the server?

### ISSUE THREAD

**Issue by pravin-d** [louischatriot/nedb#402]
I have a localDb and entries will be added from the browser. At some point all these entries will be synced to the server and stored on a mongodb database. My issue is that when I create a local entry NEdb generated an id. However once it is synced to the server I need to use the Id given by mongodb. My Options are either re-write the _id locally(which is not possible I guess), create a new entry with the server provided Id or use another which I can rename as _id for synced entries(something on these lines).. Please let me know how can this situation be handled ?

**Comment by kaizhu256** [comment]
the best solution is to ignore the "_id" field completely and create your own "id" field, that you control.
when syncing between nedb and mongodb, do not pass the _id field between them.

![screen shot 2016-05-04 at 1 05 56](https://cloud.githubusercontent.com/assets/280571/14999985/359e7c94-1195-11e6-8a37-66abe900266b.png)

**Comment by louischatriot** [comment]
+1 to @kaizhu256's proposal, as manipulating MongoDB's and NeDB's `_id` fields is bound to be messy.
