### ISSUE TITLE
Is there a way to convert query to a promise (browser client)?

### ISSUE THREAD

**Issue by pravin-d** [louischatriot/nedb#404]
I'm using angular js and would want to broadcast an event once I have a updated 2 different databases(browser client end). 
ie.
db1.insert(doc1) and db2.insert(doc2) and use $q.all() to figure out if both the db operations are completed. Is there a way to do it ?

**Comment by louischatriot** [comment]
Hello, this is not possible at the moment no and not planned. I suggest you use the `async` module to achieve that result: https://github.com/caolan/async

**Comment by pravin-d** [comment]
Current usecase is not very complicated. So I'm not sure if I have to use async on client end. Angular already provides sufficient support for promises. Let me check tho. Thank you for the quick reply.
