### ISSUE TITLE
Bugreport

### ISSUE THREAD

**Issue by simon-p-r** [louischatriot/nedb#406]
Hi

I have encountered a problem with nedb creating duplicate records using the same _id, this is a gist I have created to show bug.

https://gist.github.com/simon-p-r/f043d8885115549a90d327a34c87cf1a

OS is Windows 8.1
Node version is 5.10.1

Thanks
Simon

**Comment by louischatriot** [comment]
Works fine on my machine, and I don't see any problem with the code ... What does your script output? Thanks for the nice bug report format in any case!

**Comment by crstffr** [comment]
I too am seeing duplicate entries in the database when doing update/patch calls.  Though my setup is quite a bit more complex (using FeathersJS), my results are nearly identical to Simon's.  

* OSX v10.10.5
* Node v4.4.3
* NeDB v1.8.0

**Comment by louischatriot** [comment]
As per the readme and numerous issues priori to that, this is the expected behavior as nedb persistence uses an append only file for performance purposes. Thanks for the nice bug report format though!

**Comment by crstffr** [comment]
Thanks for the quick response. I see now that it is intentional behavior.  Setting ```db.persistence.setAutocompactionInterval(interval)``` did the trick for me.  

Cheers,
Chris

**Comment by zevero** [comment]
normally there is no need to setAutocompactionInterval
Duplicates are intentionally ignored and autocompacted at next start.
