### ISSUE TITLE
nodemon issue ? continually restarting?

### ISSUE THREAD

**Issue by andyfenelon** [louischatriot/nedb#409]
seems to not play well with nodemon 

when the app is started it keeps continually restarting /  regenerating the db

i've tried both 

`var db = new Datastore({
  filename: 'database.json',
  autoload: true
});`

and

`
db.loadDatabase();
`

to load the db, same for both.

**Comment by bdfoster** [comment]
It's going to do that... Your database file is changing whenever you use
it...

**Comment by bdfoster** [comment]
As well as its creating a backup of the filestore (same filename as your
filestore with a ~ at the end).

**Comment by louischatriot** [comment]
Yes you need to have nodemon ignore the datafile or the data directory.

**Comment by andyfenelon** [comment]
ok, thanks
