### ISSUE TITLE
#critical#  it always insert a new record when i update and use $addToSet

### ISSUE THREAD

**Issue by gaojiyong** [louischatriot/nedb#410]
before update

![qq 20160426122530](https://cloud.githubusercontent.com/assets/11253729/14807518/d27a3da0-0baf-11e6-9077-e3192fb7a1ad.png)

after update 
![2](https://cloud.githubusercontent.com/assets/11253729/14807615/9835be7a-0bb0-11e6-8678-1520f88109af.png)

code example 

![qq 20160426124519](https://cloud.githubusercontent.com/assets/11253729/14807620/9dadd676-0bb0-11e6-918c-9fc4147134d1.png)

**Comment by zevero** [comment]
Please rtfm :) its a feature - not a bug.
Nedb uses append only logic. The db-file is autocompacted on every start.

**Comment by louischatriot** [comment]
That must be the most frequently asked question, I should probably add a note top of page :)
