### ISSUE TITLE
Using nedb's syntax with mongodb

### ISSUE THREAD

**Issue by squishybanana04** [louischatriot/nedb#413]
I would like to use mongodb using the syntax that nedb has. Is there a way to do that?

**Comment by louischatriot** [comment]
Hello,

Thanks, much appreciated :) Unfortunately while NeDB copied MongoDB's syntax so that most developers would already know it, 100% upwards compatibility was not the goal. You can use an ODM such as Mongoose though to help you with a cleaner syntax. I used Mongoose in the past and it is good.
