### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by xduseko** [louischatriot/nedb#417]
Autoload feature defers all async operations until database file is completely read and ready. It there a way to defer those even more until given promise is resolved?
I have "bootstrap" script that checks if database is empty and then inserts some documents. I want to defer all other operations until it is done.

step 1
```
rm documents.nedb
```

step 2
```javascript
var db = new nedb({filename: 'documents.nedb', autoload: true});
db.count({}, function (err, count) {
  if (count === 0) {
    db.insert([{value: 1}, {value: 2}, {value: 3}]);
  }
});

//...

db.find({}, function (err, docs) {
  assert docs.length === 3;
});

```

I know I can create promise and chain all database operations, but that would be annoying. I would like to achieve it in "autoload" way.

**Comment by louischatriot** [comment]
Not possible, you need to do it at application level.
