### ISSUE TITLE
make a database read-only?

### ISSUE THREAD

**Issue by jampy** [louischatriot/nedb#418]
Is it possible to open a database file and only allow readonly access to the data contained?

I mean, raise an exception on `insert()`, `update()` etc. on collections...

**Comment by louischatriot** [comment]
Not possible but you can implement at application level

**Comment by jampy** [comment]
> but you can implement at application level

like, "don't call methods that change data" ?

**Comment by louischatriot** [comment]
In a nutshell, yes :)

**Comment by jampy** [comment]
you probably understand that doesn't help anybody..

please see this as a feature request. would it really be hard to implement this.. at database/`nedb` level?

**Comment by bdfoster** [comment]
I'm sure he'd look at a pull request if you had one...

Otherwise, you might try setting permissions to read-only on the file.

**Comment by lukasbestle** [comment]
> Otherwise, you might try setting permissions to read-only on the file.

That's not going to work unfortunately as NeDB compacts the datafile on load, so that would trigger an error.

**Comment by louischatriot** [comment]
I don't see a good rationale for implementing this kind of feature at db level, and I want to be very mindful about what makes it in the codebase. Adding a feature is not about the time it takes to integrate, but also the time it takes to maintain, cross-dependencies or impacts on other features and API creep that makes using NeDB harder.

As I said, this can easily be implemented at application level, if you need some kind of guarantee that insert/update cannot be called, you can also wrap a NeDB instance in an object only exposing the methods you want to use.
