### ISSUE TITLE
Browser version: make storage pluggable

### ISSUE THREAD

**Issue by jampy** [louischatriot/nedb#419]
As far as I can tell, the browser version of NeDB [always uses the bundled `storage.js`](https://github.com/louischatriot/nedb/blob/cadf4ef434e517e47c4e9ca1db5b89e892ff5981/browser-version/out/nedb.js#L2993) even if that module follows a pretty straightforward, abstract API that could as well be pluggable.

Please allow to optionally override the storage with a custom/alternative storage module so that different storage mechanisms can be implemented.

Something like... 

```
var myStorage = require("./my-storage");
var db = new Nedb({storage: myStorage});
```

**Comment by louischatriot** [comment]
I don't understand why it would be useful to let the user choose its storage engine?

To be clear, NeDB's browser storage engine is not optimal by far, for example the time it takes to insert an object is proportional to the number of elements in the DB. There are multiple ways to improve that dramatically which I have not implemented for lack of user requests. If you want to send a PR on the storage engine I'll happily take it but unbundling it altogether is not something I see value in.

**Comment by jampy** [comment]
A custom storage engine would simply allow different kinds of storage options. The current storage engine already makes use of various storage systems available (via `localforage`), so it is plausible that a user might want to influence the way it works or even implement a completely/different new one.

The current storage engine is wonderfully simple (something like a virtual file system) and could be replaced by a custom implementation without great effort.

In my case I'd like to enhance the storage system by adding some kind of remote sync (deliberately at "file" level) - you might think of it like a cloud backup. Implementing that at collection level would be overkill, but at file level (without depending on the *contents*/schema of the collections) it would be really simple. You see that this is very implementation specific.

Since I'm planning a new, large desktop-like application running completely in the browser (or Electron) it's crucial to have a solid in-browser database (`NeDB` seems one of the best options for the moment) and this project would require two-way syncing with a centralized server. There is no concurrency problem because it's okay if only one user can have access to the database at a time.

>the time it takes to insert an object is proportional to the number of elements in the DB

That's something that I would love to optimize and having a pluggable storage engine would make development easier even in that regard.

>unbundling it altogether is not something I see value in.

My suggestion is like, [“batteries included but removable”](https://clusterhq.com/2014/12/08/docker-extensions/): just make it an option.

IMHO this should be easily doable with something like...

`storage = options.storage ? options.storage : require('./storage');`

...but I'm not that familiar with the NeDB source code so you probably could add that relatively quickly. At least I hope... :-)

What do you think now?
