### ISSUE TITLE
Have any ORM support nedb?

### ISSUE THREAD

**Issue by youxiachai** [louischatriot/nedb#43]
nedb api like mongodb ,that means it available support mongoose?

**Comment by luislobo** [comment]
Actually, yes: waterline (orm) can use https://github.com/adityamukho/sails-nedb

**Comment by coderofsalvation** [comment]
http://fortunejs.com as well, it allows you to create api's with relational entities

**Comment by cosmosgenius** [comment]
https://github.com/scottwrobinson/camo was made for nedb compatible with mongodb

**Comment by andyhu** [comment]
https://github.com/andyhu/waterline-nedb

**Comment by gayanhewa** [comment]
Found this https://github.com/aerys/mongoose-nedb , but not sure of the state of the project or what limitations it has.

**Comment by andyhu** [comment]
@gayanhewa Looks like the project is dead

**Comment by bdfoster** [comment]
https://github.com/bdfoster/nomatic-data

An adapter could be written fairly easily for NeDB.

**Comment by JamesMGreene** [comment]
There is also FeathersJS

https://github.com/feathersjs/feathers-nedb
