### ISSUE TITLE
Using nedb inside angularjs inside electron

### ISSUE THREAD

**Issue by mkermani144** [louischatriot/nedb#449]
Hi, 
I want to use nedb inside angularjs inside electron. How should I do that?
I tried importing nedb inside `main.js` of electron app, and use it inside angularjs files (e.g. angular's factory files), but it doesn't work. angularjs does not know about the modules imported in electron's `main.js`.
I also read #334, but I still have no idea.
Should I use something like [browserify](https://github.com/substack/node-browserify)?

**Comment by black-snow** [comment]
You can use nedb in the main process and communicate via ipc or you can use it in any renderer. Really depends on your scenario.

**Comment by mkermani144** [comment]
Oh, sorry about that :(. I forgot to install `nedb` and put it in my `node_modules` and tried to use global one. Now everything works well.
