### ISSUE TITLE
Error: More than 10% of the data file is corrupt...

### ISSUE THREAD

**Issue by mnemanja** [louischatriot/nedb#455]
I have a simple setup with one db file and reading from 1 line that I've previously supplied through the api (insert). Since then no other operations have been performed upon the database.

Now all of the sudden I'm receiving the following error, and nothing I do seems to effect it:
```
if (err) { throw err; }
               ^

Error: More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss
    at Persistence.treatRawData (C:\www\issues-configurator\node_modules\nedb\lib\persistence.js:242:11)
    at C:\www\issues-configurator\node_modules\nedb\lib\persistence.js:281:38
    at tryToString (fs.js:455:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by louischatriot** [comment]
Hello,

Thanks for reaching out. Can you please follow the bug reporting guidelines (see end of the readme), this kind of report unfortunately makes debugging almost impossible.

**Comment by mnemanja** [comment]
Hi,

I appreciate the response and the guide to how to submit next issues.

As for this one it has been fixed eighter by trying to populate the db or something else but I was not able to notice what exactly.
If it occurs again and I'm able to simulate it I'll be sure to submit a proper bug. The only problem that I see here is that I didn't understand what caused the bug and thus wasn't able to simulate it.

**Comment by martinsookael** [comment]
@mnemanja thank you for bringing it up. 
I think for me as well the db corrupting is one of the biggest hassles with nedb. 

I've found out, that in a lot of the cases this error is actually my fault - 
for example sometimes i forget to put the db files to .gitignore and sometimes the files get both modified, living a huge <<<<<<<<<HEAD to the files etc. The other times I tend not to have enough time to figure out whose fault it was and how this could be reproduced. 

One way i'm "solving" this, is with adding corruptAlertThreshold to 1, which basically disables DB notifications of data corruptions. It works for my prototyping projects, but would not be the best solution for your production apps.

`var dbMemberBerries = new Datastore({ filename:"/Memberberries.jsonl", corruptAlertThreshold: 1 })
`

**Comment by mnemanja** [comment]
@martinsookael 
Thanks for the conversation on this issue, sure helps.

Now that I saw this and checked my code I've actually used it to be able to perform some other operations on the DB, and now when I've removed it it seems to have continued to work nicely.

I'll keep it handy for the next time (if) this happens. 
Thanks and keep up with the good work :)

**Comment by louischatriot** [comment]
Thanks :)

So that was in fact a big reason for me to ask to report using the guidelines, they usually help catching user mistakes so that bug report are more often about actual nedb bugs - if nedb files were often corrupt I do not see why people would use it, but that is not the case, all bug reports similar to yours are indeed people who changed the db file itself :)

Btw setting the threshold to 1 is doable but as @martinsookael  says don't do that in production, this check is here for a reason, namely preventing accidental corruption of part of the file (e.g. <<<<<HEAD) from causing data loss.

**Comment by martinsookael** [comment]
As we are already on the topic. 
Is there a tool for validating what exactly is considered corrupt in the file?

For example I've got a 4MB file, which SOMETIMES logs this in the server: 
```
app-0 (err): Error: More than 10% of the data file is corrupt, the wrong beforeDeserialization hook may be used. Cautiously refusing to start NeDB to prevent dataloss
app-0 (err):     at Persistence.treatRawData (/app/lib/j2y-npm/node_modules/nedb/lib/persistence.js:242:11)
app-0 (err):     at /app/lib/j2y-npm/node_modules/nedb/lib/persistence.js:281:38
app-0 (err):     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```

**Comment by xuling5300** [comment]
@martinsookael @mnemanja You mean put this code:
'var dbMemberBerries = new Datastore({ filename:"/Memberberries.jsonl", corruptAlertThreshold: 1 })'
to where? Sorry I'm sure really understand how to fix this issue. Please helping~~ Thanks so much.

**Comment by xuling5300** [comment]
@martinsookael @mnemanja 
I'm not sure really understand...typing mistake :)

**Comment by xuling5300** [comment]
I don't know why, I only delete \nedb\instances.db, and this issue was gone.

**Comment by martinsookael** [comment]
If it is possible to just remove the old database, then just deleting the old db "solves" this.
You will loose all the data, but you'll get a brand new db, which does not give this error.

**Comment by xuling5300** [comment]
But, Actually this issue was not solved. ......

**Comment by paulshapiro** [comment]
@louischatriot  I just got this. This is sometime after I have enabled DB compaction. It occurred after I made a change to my app's data and then terminated the app. So I have a strong feeling that it's caused by a DB compaction operation which does not complete. Could that be possible?

**Comment by dionisoros** [comment]
I had the same problem when I was adding a new "users.json" file and adding a new line. I've just deleted all the content from "users.json" file and restart the server and everything was fine.

**Comment by NguyenQuocVuong-git** [comment]
Has this issue been resolved? I'm still experiencing it quite often, and it's very frustrating. Can someone help me fix this issue? I don’t want to have to switch to a different database :(
`node:13868) UnhandledPromiseRejectionWarning: Error: 25% of the data file is corrupt, more than given corruptAlertThreshold (10%). Cautiously refusing to start NeDB to prevent dataloss.
    at LineStream.eval (webpack:///./node_modules/@seald-io/nedb/lib/persistence.js?:272:27)
    at LineStream.emit (events.js:315:20)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:13868) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting 
a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:13868) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
