### ISSUE TITLE
Unable to load, when the database file is too large

### ISSUE THREAD

**Issue by milu2003** [louischatriot/nedb#457]
![image](https://cloud.githubusercontent.com/assets/15957433/18814457/916e79ac-8346-11e6-8034-b95a73ccbf5a.png)

I was developed with electron。There is an error in the image above.
I finally found that the database file is too large, to see a bit, about 200MB

If I delete the file, the program is normal.

How to solve this problem？

**Comment by ornic** [comment]
Auto-compactification every once in a while or, if the data set is actually above 256Mb, use another DB. NeDB use `Buffer` to load file from disk to memory and its limit for most systems is 256Mb.

https://github.com/louischatriot/nedb/issues/389

**Comment by milu2003** [comment]
ok。Then I switched to leveldb.Speed is also very fast
