### ISSUE TITLE
Can update multi: true have multiple selectors?

### ISSUE THREAD

**Issue by yourfavorite** [louischatriot/nedb#466]
I gave it a shot myself but what I have doesn't work. Is there any way to get it to update multiple documents this way or will I have to just call update once per document I'd like to update?

```
db.settings.insert([{ _id: '001', a: 5 }, { _id: '002', a: 42 }], () => {
  console.log('inserted 2');
});

db.settings.update([{ _id: '001' }, { _id: '002' }], [{ a: 6 }, { a: 43 }], { multi: true }, err => {
  console.log('err is', err);
});
```

**Comment by Loksly** [comment]
The syntax is:

    db.update(query, update, options, callback);

so if you want to update both documents you should use a query criteria that matches both documents,  try something like:

    var query = { _id: { $in: [ '001', '002' ] } };
    var update = { $inc: { a:  1 } };
    var options = { multi: true };
    var cb = console.error;

    db.update(query, update, options, callback);

**Comment by yourfavorite** [comment]
Thanks @Loksly! I got that working, but let's assume that I didn't want to just increment the numbers, but instead wanted to update to different numbers. This is what I tried:

```
const query = { _id: { $in: ['001', '002'] } };
const update = { $set: [{ a: 1 }, { a: 2 }] };
const options = { multi: true };
const cb = console.error;

db.settings.update(query, update, options, cb)
```

**Comment by Loksly** [comment]
Hi @yourfavorite, as far as I can understand reading the code:

    lastStepModifierFunctions.$set = function (obj, field, value) {
      obj[field] = value;
    };
    
https://github.com/louischatriot/nedb/blob/master/lib/model.js#L252

you can't update both documents with different values using $set, I might be wrong but that's what I guess.
Is it really hard to send two updates to the database?

**Comment by yourfavorite** [comment]
It is not hard. Just thought there might be a more efficient way to update several documents at once. Thanks for your help!

**Comment by Loksly** [comment]
you are welcome.
have a nice day

**Comment by vifird** [comment]
Any solution? In MySQL, this is can be resolved used `ON CONFLICT DO UPDATE SET`, does "NeDB" have solution?
