### ISSUE TITLE
Update subarray

### ISSUE THREAD

**Issue by martiera** [louischatriot/nedb#471]
Hello, can't insert subarray, maybe I'm doing something wrong. Can you point me how to do in correct way?
Example of data structure:
{ _id: 'id6', fruits: [{name:'orange', size:['small']},{name:‘pear’, size:[]}, {name: ‘apple’, size: ['small', ‘medium']} ] }

db.update({ _id: 'id6', "fruits.name": 'pear' }, { $addToSet: { "fruits.size" : "medium" } }, {}, function(err, numReplaced) {
                       console.log('Replaced: %s', numReplaced)
})

Console show: 
Replaced: 1

db is not updated.

**Comment by Loksly** [comment]
Hi martiera,
the $addToSet needs to know what is the subdocument you want to change.
```javascript
db.update({ _id: 'id6', "fruits.name": 'pear' }, { $addToSet: { "fruits.1.size" : "medium" } }, {}, next);
```


I don't know how to help you to discover what is the number of the subelement inside fruits without a get before the update.

Check this example:
https://jsfiddle.net/yzr1f9ec/

**Comment by martiera** [comment]
Thank you! That way it works.

**Comment by neody** [comment]
how to find fruits.1.size?

**Comment by JamesMGreene** [comment]
@neody: In their case above, I think that may just be a known target index.  However, if you are looking for general support of positional array operations, you may want to check out existing PR #438.
