### ISSUE TITLE
can multiple processes write to same db?

### ISSUE THREAD

**Issue by chovy** [louischatriot/nedb#479]
I've found issues when multiple process update flat json files...sometimes the file will get corrupt.

I'm curious if nedb has solved this or if I should be careful not to update the database asynchronously or from multiple processes.

**Comment by louischatriot** [comment]
Hello, the answer is no, you should never access the same nedb instance from multiple processes. Typically it would not work, as the first process will get a lock on writing to the data file.

**Comment by chovy** [comment]
is it possible to wait for the lock to be released?

**Comment by m4heshd** [comment]
There should definitely be an unlocking mechanism since this is an essential feature.
