### ISSUE TITLE
How do I set localStorage instead of IndexedDB as best method? (using electron)

### ISSUE THREAD

**Issue by rodrigoelicer** [louischatriot/nedb#482]
Basically what the issue says... I want to use NeDB and create a db but be able to keep it as a file somewhere in my project. I'm using electron and right now it's going on the browser as an IndexedDB

> If you specify a filename, the database will be persistent, and automatically select the best storage method available (IndexedDB, WebSQL or localStorage) depending on the browser.

How do I manually set it as a localStorage?

**Comment by rodrigoelicer** [comment]
Realized it was because I'm using electron and it saves the db on client instead of server

**Comment by facelesspanda** [comment]
As far as I understand NeDB and electron, you don't need the browser version.

If you want persistence in a file you choose the location of, go for the non-browser version, electron can run it without problems. Works for me.

**Comment by rodrigoelicer** [comment]
Thanks for replying but i'm still a bit newbie in all of this. I do choose the file location in my app but don't know if it's the non-browser version or not. How do I change that? For what i'm getting, it seems like my app is running on the browser version.

**Comment by facelesspanda** [comment]
I looked back at my code and at nedb's readme, and I don't think "browser version or not" is relevant for electron.

Do you bundle your scripts, with webpack or something?

How do you create your NeDB Store object and how do you import its class ?

The info you give is really not much.

**Comment by rodrigoelicer** [comment]
Yeah sorry for the lack of info, I thought it was something more general.

As I said before i'm still learning and right now i'm using a "starter" repo so don't know every of its configuration yet. However I do believe i'm using webpack to bundle. 

I'm using Angular2 and for the db creation I did a service which exports it like this:
```
declare var require: any;
let Datastore = require('nedb');

export class Database {

    constructor (){
        this.db = new Datastore({ filename: 'DB_T.db', autoload: true });
    }

   //...
}
```

Then on the Component I import it on the constructor like this:
```
import { Component, OnInit } from '@angular/core';
import { Database } from '../shared/database.service';

@Component({
  selector: 'app-market',
  templateUrl: './market.component.html'
})
export class MarketComponent implements OnInit {

  constructor(private db : Database) { }

  //...
}
```
I also have to say that the db persists but on the browsers as IndexedDB, not as a file on the project folder.

Sorry if I cannot give enough info for this since i'm still a newbie. Also thanks for trying to help me out with this! Here's the repo i'm using in case you want to see deeper: https://github.com/rodrigoelicer/electron-testing-app

**Comment by facelesspanda** [comment]
ok so you basically have kinda the same setup as me. This makes it easier.

I'd say: check your whole machine for a `DB_T.db` file. As it is, your file could be somewhere in your node_modules folder under electron if you launch your test build with `electron <app>`, or somewhere else.

To be really sure, change your DB filepath to somewhere predictable, using `path` functions (`import * as path from 'path'`), and `app.getAppPath()`
(it's an electron main process module, so you'd need to import it like that : `const {app} = require('electron').remote;`

---
For reference, my db service looks like this:

```typescript
import { Injectable, NgZone } from '@angular/core';

import * as DataStore from 'nedb'; // <== I import NeDB liike that.

//... other imports

@Injectable()
export class WikiDbService {
    //...
    private db: DataStore;

    constructor(private _zone: NgZone) {
        this.db = new DataStore(
            {
                filename: path.join(app.getAppPath(), "wiki.db"), // <== your db file name
                autoload: true, // <== I set it to autoload for personal needs
                onload: (err) => {
                    if (!err) {
                        this.db.find<WikiItem>({},
                            (e, docs) => {
                                if (!e) {
                                    this._zone.run(() =>
                                        this.sub.next(docs)
                                    )
                                }
                            })
                    } else {
                        //notify error
                    }
                }
            });
    }
    //...
}
```

So in the end, it's not much different.

**Comment by rodrigoelicer** [comment]
I tried what you proposed but I'm getting the following error:
```
TypeError: fs.readFileSync is not a function main.bundle.js:66890:39
```
My code looks like this now: (I tried with "import * as path from 'path';" but doesn't work. It says that it cannot find module 'path'. Same for the way you import nedb)
```
declare var require: any;
let Datastore = require('nedb');

const { app } = require('electron').remote; // <== new
let path = require('path'); // <== new
//import * as path from 'path';

export class Database {

    constructor (){
        this.db = new Datastore({
          filename: path.join(app.getAppPath(),"DB_T.db"), // <== new
          autoload: true });
    }

    private db;
    //...
}
```

Thanks again for still helping me! Much appreciated.

**Comment by facelesspanda** [comment]
It is though. `readFileSync` is a function of Node's fs object.

This got out of my scope. I could spend time doing research to help you, but don't have that time, sorry. Hope someone else can help you.

**Comment by rodrigoelicer** [comment]
No problem! Thanks anyway.

**Comment by krisak** [comment]
I think you are mixing things up. If you look into electron docs http://electron.atom.io/docs/ you will se main process and renderer process. Main process is basicaly the node.js bundeled part of electron (that spawns windows and has node.js available). The render process is the regular browser you would get when doing websites.

You cant use fs (functions from node.js core) in the browser render process. 

I asume you want to persist the data in some file - well you have to do it in the main process that hase node.js available and can save files. Its like when doing regular websites but instead of connecting to server somewhere else, you are connecting to node running on your machine (your electron app). You can find in documentation how these two parts can communicate with each other.

**Comment by rodrigoelicer** [comment]
Thanks mate! However I'm now able to import the db on the renderer process and persist it with a file. I searched for different repos and it seems to be something with webpack, where you have to set the target as 'electron-renderer'. 

Here's my [test repository](https://github.com/rodrigoelicer/electron-angular2-nedb) in case someone want to give a deep look since I don't really know much about webpack and those stuffs. I give the credit to hawok for setting up the webpack config though.

**Comment by Yvanovitch** [comment]
Hi, I think the reason is because browserify convert the "require" to the browser process, so nedb can only access the browser storage.
You need to use "window.require" to stay on the nodejs side and access the localStorage.
It is the same problem for `TypeError: fs.readFileSync is not a function main.bundle.js:66890:39`, you need to use 'window.require('fs').
Hope it helped.
