### ISSUE TITLE
Electron  db.find() at the Main Process returns Empty array 

### ISSUE THREAD

**Issue by Revln9** [louischatriot/nedb#484]
https://github.com/chentsulin/electron-react-boilerplate

this is the boilerplate that i use and when you load nedb in app\main.developement.js ,  it will insert docs just fine but when you perform a read on it and pass it to the IpcMain (example) it will return an empty array [ ] no matter what.

i'm using the path join described in the readme but still no luck, any idea about what goes wrong?

**Comment by facelesspanda** [comment]
The methods on the store are not supposed to *return* data.
You give them a callback that will take data and do what you want or need with them.
I use `find` like this to load my collection into a rxjs BehaviorSubject:
```typescript
this._db.find<Stereotype>({},
(e,docs) => {
    if(!e) {
        this._zone.run(() =>
            this._sub.next(docs)
        )
    }
});
```
In short : read the examples in the wiki

**Comment by Revln9** [comment]
i use this perfectly fine on the app "browser" , and yes i pass the data to a callback , still no luck , tested on windows 8 and windows 7

**Comment by facelesspanda** [comment]
Do you mean that `docs` is empty or that there is an error?

**Comment by Revln9** [comment]
no error no docs , just an empty array , all the time.

**Comment by facelesspanda** [comment]
Are you sure there are data in your db? Is there an error when you insert docs in it?

**Comment by Revln9** [comment]
the insert method works just fine i can insert docs and can see the database file size growing i can find my docs inside it , the problem is in the read operation , even if u write
` db.find({ }, function(err , docs){ console.log(docs) })` it will return empty all the time

**Comment by facelesspanda** [comment]
I have setup my own angular+wepback project, so I'm not sure what `main.development.js` exactly is or does but you're now talking about the electron Main Process.

This begs some new questions in my mind:

1. Do you write and read on the same `db` object?
2. Do you write and read in the same electron process?

**Comment by Revln9** [comment]
check this link https://github.com/chentsulin/electron-react-boilerplate , this is the boilerplate that i use , and inside of the folder `app` , there's a file called `main.developement.js` which is the main process of this electron app , if i use nedb there , the read will not work and give only empty array without error , but insert method does work. 
If you require and use nedb in the view , react or angular or whatever , both read and insert works just fine.

The thing that i've noticed with nedb is that the library is splitted in two , one version for the browser , and one version for other environments(node , electron...) and i suspect that the nedb library that i'm using is returning the browser version in both render processes ( main , renderer )... but i'm not sure about it.

**Comment by facelesspanda** [comment]
Yeah if you get the browser version in the main process it can be where the issue resides. Especially if everything works in the renderer process.

I don't actually know what module is returned if you just require `nedb`.

**Comment by Revln9** [comment]
Fixed , it wasn't the library version i was overrinding  some variables at the ENV process including the variable that i used for path join... my bad u.u

Thanks again for your valuable help.

**Comment by facelesspanda** [comment]
Haha we all do these x)

**Comment by shashannkbawa** [comment]
how could I send response inside dB.find({}). if I console log m data then it is perfectly fine. but I couldn't send the response...in the client-side, it only shows undefined
