### ISSUE TITLE
Storing React components in NeDB (contains $$typeof property)

### ISSUE THREAD

**Issue by FerusAndBeyond** [louischatriot/nedb#491]
I'm notified that there should be no $ in field. But the react components all have $$typeof in them, is there any way to do it?

**Comment by grind086** [comment]
Any reason you can't just use `JSON.stringify`? Otherwise you could clone the object and change any fields with `$$` to have `__` (for example), then reverse the process on load.

**Comment by FerusAndBeyond** [comment]
I thought about cloning the object and changing the fields, but they could be arbitrarly nested which would make it slow. I didn't think about JSON.stringify since NeDB stores it as JSON aswell it would be stringified twice, but I tried it now and it works fine, I just have to do some regex too remove escaped " (\"). Thanks for the tip.
