### ISSUE TITLE
Confusing about option upsert when update

### ISSUE THREAD

**Issue by KevinOfNeu** [louischatriot/nedb#495]
db.insert will generate unique _id for each item, but when use db.update with upsert option, all _id is the same, So, next time when you open database file, only one record will left. That is very confusing and cannot find refs from README

**Comment by fjeddy** [comment]
The reference (Docs) state that each update request is added a new line with an identical id, when the database is reloaded, it will purge itself by removing all old arrays (Keeping the last one). This is done for performance reasons.

From the [Readme ](https://github.com/louischatriot/nedb)under **Persistance**

> Under the hood, NeDB's persistence uses an append-only format, meaning that all updates and deletes actually result in lines added at the end of the datafile, for performance reasons. The database is automatically compacted (i.e. put back in the one-line-per-document format) every time you load each database within your application.

**Comment by KevinOfNeu** [comment]
@fjeddy thx
