### ISSUE TITLE
How can I save an array of objects?

### ISSUE THREAD

**Issue by thiagohagy** [louischatriot/nedb#498]
I have this object
{
  name: 'any',
  contacts: [
     {name: 'jose', phone: 1234} ,
     {name: 'jose', phone: 1234}    
 ],
 obs : 'anything here',
address : 'street 1'
}

but when I try to save ,Nedb returns this for me:
Error: Field names cannot begin with the $ character(…)

If I remove the contacts field , then it saves
I'm starting learning  Nedb and I stopped in this problem

**Comment by emrecanozkok** [comment]
JSON.stringify(yourobject)

**Comment by thiagohagy** [comment]
I found out what was the problem, angular create a field $$hashKey  on the array and this was causing the error. I just used :var newArray = angular.toJson(oldArray) and then it saved.
