### ISSUE TITLE
delete doesn't work

### ISSUE THREAD

**Issue by abbddo** [louischatriot/nedb#509]
this is my order to delete a data from my db 

``` chats.remove({ _id: chatId }, {}, function (err, numRemoved)  // chatId = 1001131507377 ```

the database before running the remove order 
``` {"_id":1001131507377,"chatTitle":"test group","AddedBy":"159263523 - @rrbot - Abd"}```

the data base after running the remove order 

``` {"_id":1001131507377,"chatTitle":"test group","AddedBy":"159263523 - @rrbot - Abd"} ```
```{"$$deleted":true,"_id":1001131507377} ```

it passes and doesn't show any error

**Comment by rococtz** [comment]
This is quote from the documentation. Does it answer your question?

> Under the hood, NeDB's persistence uses an append-only format, meaning that all updates and deletes actually result in lines added at the end of the datafile, for performance reasons. The database is automatically compacted (i.e. put back in the one-line-per-document format) every time you load each database within your application.
