### ISSUE TITLE
Datastore(DB) File is not loading after building in electron APP.

### ISSUE THREAD

**Issue by javeedrahman** [louischatriot/nedb#510]
Hi Guys,
I had the same issues and i have tried it this way (my code)
```
var electron = require('electron');
const app = electron.remote.app;
var userData = app.getAppPath('userData');
db = new Datastore({ filename: userData+'/db/persons.db', autoload: true });
```
Its working when i run npm start. but after building the APP using electron-builder
i am getting error in linux and MAC. its only on build.

![errorpath](https://cloud.githubusercontent.com/assets/3214829/26275434/b0f24604-3d7d-11e7-8e9b-631c1eb80abf.png)

Please some help,
Thanks in advance.

**Comment by javeedrahman** [comment]
Hi guys,

This is my mistake. Its working fine now. I have used app.getAppPath() instead of app.getPath('userData')
```
var electron = require('electron');
const app = electron.remote.app;
var userData = app.getAppPath('userData');   <-------- Here i made issues this is app.getPath('userData')
db = new Datastore({ filename: userData+'/db/persons.db', autoload: true });
```
I have tested the build in MAC, LINUX UBUNTU and WINDOWS. working fine.

Thank You :)

**Comment by alexey-sh** [comment]
@javeedrahman did you see `not found in /Users/.../my.app/Contents/Resources/app.asar` error?
