### ISSUE TITLE
Getting all data from fieldName?

### ISSUE THREAD

**Issue by dannysmc95** [louischatriot/nedb#513]
HI,

Just started using this, and it's great, but I am having issues with actually using it? I only want to use it to set and get persistent data?

But it seems I can set data but I can't just get it back simply? so why is everything:

db.find({ planet: 'earth' }); ? Is there nothing to allow me to just retrieve all data inside the planet array? if it was an array?

Thanks,
Danny

**Comment by JamesMGreene** [comment]
I'd suggest you read the NeDB README (for the first time, or again).  It contains many examples of working with arrays.
