### ISSUE TITLE
Is there a way to make queries sync?, btw awesome job with the module.

### ISSUE THREAD

**Issue by p4t0g3n0** [louischatriot/nedb#528]

**Comment by JamesMGreene** [comment]
No trivial way to do so, no.

If you need something like that right now that is persistent (not in-memory) and runs on Node.js (not in the browser), you can try out this other database offering that I found a while ago: https://www.npmjs.com/package/diskdb

**Comment by p4t0g3n0** [comment]
Thanks, I had forgotten completely that module. :)
