### ISSUE TITLE
Failed to flush to storage

### ISSUE THREAD

**Issue by xjj8567320** [louischatriot/nedb#538]
when i run an electron + angular project with nedb ,i get this error, how can i resolve the problem? 
![image](https://user-images.githubusercontent.com/19648679/35203216-32eb783c-ff62-11e7-8573-3ddbee858bce.png)

**Comment by JamesMGreene** [comment]
What type of system are you running it on? (OS, 32-bit/64-bit, etc.)

**Comment by xjj8567320** [comment]
no  windows / 64-bit

**Comment by JamesMGreene** [comment]
Resolved or given up? If resolved, please share how. Thanks!

**Comment by bushev** [comment]
I have the same issue on Windows 7. MacOS version works perfectly.

**Comment by Zhou-Bill** [comment]
so how to solve in windows?

**Comment by bushev** [comment]
Unfortunately no, switched to TingoDB.
