### ISSUE TITLE
Documentation: Join/Merge

### ISSUE THREAD

**Issue by Extarys** [louischatriot/nedb#541]
How can I join 2 datasets and if possible sort them?

I'd like to join the artist_id from a song to the id of the artists dataset and sort the results by artists.

My previous code, before splitting things:
```
Database.table.Songs.find({}).sort({ artist: 1, album: 1 }, function(err, data) {
    cb(data)
});
```

The issue is that I might need to display all artists or all albums made by an artist and I think making a separate dataset for this is better.

What I would like
```
Database.table.Songs.find({}, function(err, data) {
            data.forEach(function(action) {
                Database.table.Artists.findOne({ _id: data.artist_id }, function (err, artist) {
                    cb(data);
                });
            });
});
```

or
```
Database.table.Songs.find({}).join(Database.table.Artists: {artist_id, _id}).sort({artist_name: 1}, function(err, data) {
            data.forEach(function(action) {
                Database.table.Artists.findOne({ _id: data.artist_id }, function (err, artist) {
                    cb(data);
                });
            });
});
```
Is this possible? the documentation doesn't cover this.

**Comment by JamesMGreene** [comment]
Sounds like you’re trying to treat NeDB as relational database (SQL) rather than document store (NoSQL). Not recommended.

**Comment by JamesMGreene** [comment]
Sounds like you’re trying to treat NeDB as a relational database (SQL) rather than a document store (NoSQL). Not recommended... wrong paradigm.

**Comment by Extarys** [comment]
Hmm, well many NoSQL databases offer Joins ;) anyway thx

**Comment by rayfoss** [comment]
https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-1

MongoDB does it... if you were looking for a node based mongodb with api parity to facility development... NeDB is not it. It's really only ever useful for hackathon level prototypes or self contained electron/mobile apps and small offline apps.

You might have better luck with https://github.com/Ivshti/linvodb3 or just quit MongoDB all together and go full level.
