### ISSUE TITLE
errors in nightly backup on portal.duranc.com

### ISSUE THREAD

**Issue by vamsiduranc** [louischatriot/nedb#546]
we see continuous errors in pm2 logs related to nightly backup. So stopping the nightly back up process now in pm2. please check once.

4|nightly- |
4|nightly- | 2018-03-01T10:43:36.217Z mongodump stderr: 2018-03-01T05:43:36.217-0500    [###############.........]  duranc.fs.chunks  269164/422907  (63.6%)
4|nightly- |
4|nightly- | 2018-03-01T10:43:39.217Z mongodump stderr: 2018-03-01T05:43:39.217-0500    [###############.........]  duranc.fs.chunks  269489/422907  (63.7%)
4|nightly- |
4|nightly- | 2018-03-01T10:43:42.217Z mongodump stderr: 2018-03-01T05:43:42.216-0500    [###############.........]  duranc.fs.chunks  269729/422907  (63.8%)
4|nightly- |
4|nightly- | 2018-03-01T10:43:45.217Z mongodump stderr: 2018-03-01T05:43:45.216-0500    [###############.........]  duranc.fs.chunks  269969/422907  (63.8%)
4|nightly- |
4|nightly- | 2018-03-01T10:43:48.217Z mongodump stderr: 2018-03-01T05:43:48.216-0500    [###############.........]  duranc.fs.chunks  270285/422907  (63.9%)
4|nightly- |
4|nightly- | 2018-03-01T10:43:51.217Z mongodump stderr: 2018-03-01T05:43:51.217-0500    [###############.........]  duranc.fs.chunks  270522/422907  (64.0%)
4|nightly- |
4|nightly- | 2018-03-01T10:43:54.217Z mongodump stderr: 2018-03-01T05:43:54.216-0500    [###############.........]  duranc.fs.chunks  270839/422907  (64.0%)
4|nightly- |

4|nightly- | 2018-03-01T10:43:57.217Z mongodump stderr: 2018-03-01T05:43:57.216-0500    [###############.........]  duranc.fs.chunks  271076/422907  (64.1%)
4|nightly- | 2018-03-01T10:44:00.217Z mongodump stderr: 2018-03-01T05:44:00.216-0500    [###############.........]  duranc.fs.chunks  271392/422907  (64.2%)
4|nightly- | 2018-03-01T10:44:03.217Z mongodump stderr: 2018-03-01T05:44:03.216-0500    [###############.........]  duranc.fs.chunks  271630/422907  (64.2%)
4|nightly- | 2018-03-01T10:44:06.217Z mongodump stderr: 2018-03-01T05:44:06.217-0500    [###############.........]  duranc.fs.chunks  271944/422907  (64.3%)
4|nightly- | 2018-03-01T10:44:09.217Z mongodump stderr: 2018-03-01T05:44:09.217-0500    [###############.........]  duranc.fs.chunks  272181/422907  (64.4%)
4|nightly- | 2018-03-01T10:44:12.217Z mongodump stderr: 2018-03-01T05:44:12.216-0500    [###############.........]  duranc.fs.chunks  272497/422907  (64.4%)
4|nightly- | 2018-03-01T10:44:15.217Z mongodump stderr: 2018-03-01T05:44:15.216-0500    [###############.........]  duranc.fs.chunks  272735/422907  (64.5%)
4|nightly- | 2018-03-01T10:44:18.217Z mongodump stderr: 2018-03-01T05:44:18.216-0500    [###############.........]  duranc.fs.chunks  273055/422907  (64.6%)
4|nightly- | 2018-03-01T10:44:21.217Z mongodump stderr: 2018-03-01T05:44:21.216-0500    [###############.........]  duranc.fs.chunks  273299/422907  (64.6%)
4|nightly- | 2018-03-01T10:44:24.217Z mongodump stderr: 2018-03-01T05:44:24.216-0500    [###############.........]  duranc.fs.chunks  273542/422907  (64.7%)
4|nightly- | 2018-03-01T10:44:27.217Z mongodump stderr: 2018-03-01T05:44:27.216-0500    [###############.........]  duranc.fs.chunks  273867/422907  (64.8%)
4|nightly- | 2018-03-01T10:44:30.217Z mongodump stderr: 2018-03-01T05:44:30.216-0500    [###############.........]  duranc.fs.chunks  274113/422907  (64.8%)
4|nightly- | 2018-03-01T10:44:33.217Z mongodump stderr: 2018-03-01T05:44:33.216-0500    [###############.........]  duranc.fs.chunks  274441/422907  (64.9%)
4|nightly- | 2018-03-01T10:44:36.217Z mongodump stderr: 2018-03-01T05:44:36.216-0500    [###############.........]  duranc.fs.chunks  274684/422907  (65.0%)
^C
sfrees@portal:/home/app/duranc-portal/uploads$ pm2 status
┌────────────────┬────┬──────┬───────┬────────┬─────────┬────────┬─────┬────────────┬────────┬──────────┐
│ App name       │ id │ mode │ pid   │ status │ restart │ uptime │ cpu │ mem        │ user   │ watching │
├────────────────┼────┼──────┼───────┼────────┼─────────┼────────┼─────┼────────────┼────────┼──────────┤
│ nightly-backup │ 4  │ fork │ 28737 │ online │ 1       │ 42h    │ 0%  │ 87.2 MB    │ sfrees │ disabled │
│ portal         │ 3  │ fork │ 20348 │ online │ 5       │ 15h    │ 0%  │ 276.6 MB   │ sfrees │ disabled │
└────────────────┴────┴──────┴───────┴────────┴─────────┴────────┴─────┴────────────┴────────┴──────────┘

**Comment by JamesMGreene** [comment]
Looks like you are using MongoDB rather than NeDB...?  Or are you trying to use MongoDB tools (i.e. `mongodump`) with NeDB?

**Comment by vamsiduranc** [comment]
Very sorry for the confusion. this was to be posted elsewhere. Please ignore. Thank you!
