### ISSUE TITLE
🚀🚀🚀 a way to fix large nedb file 🚀🚀🚀

### ISSUE THREAD

**Issue by crapthings** [louischatriot/nedb#548]
my nedb is about 300mb and i can't load it after server restart.

![image](https://user-images.githubusercontent.com/1147704/37640412-6866372a-2c50-11e8-9df4-05cde7df31e7.png)

so  i open it with sublime

1. unwrap line
![image](https://user-images.githubusercontent.com/1147704/37640435-88733af4-2c50-11e8-9722-5f79fd9a0ad1.png)

2. sort line
![image](https://user-images.githubusercontent.com/1147704/37640454-9f59871e-2c50-11e8-9861-e3d5ca1416d6.png)

3. unique
![image](https://user-images.githubusercontent.com/1147704/37640479-c47d1d58-2c50-11e8-8e3d-265406cec0d9.png)

after it it will reduce the size
![image](https://user-images.githubusercontent.com/1147704/37640561-31db818c-2c51-11e8-8418-02fa43babd15.png)

then after load it to nedb the file will about 6.5 mb 

i don't know why it have duplicate records, maybe i haven't use unique on it, or my express server is wrong. but after all i can load it and transfer it to mongo

https://github.com/crapthings/nedb-to-mongodb

**Comment by louischatriot** [comment]
Note that this is the intended behaviour, as per https://github.com/louischatriot/nedb#persistence

300MB seems like a lot for a NeDB database and the kind of dataset you should start using Mongo with, though you're still far from the RAM limits of the V8 so it should load on standard hardware.

**Comment by crapthings** [comment]
so will remove duplicate records impact findOne ?
