### ISSUE TITLE
why automatic records remove when i open my desktop app?

### ISSUE THREAD

**Issue by hiteshkanani** [louischatriot/nedb#550]
Recently added record remove when open desktop app again. can you help me for this.

here is my code

var Datastore = require('nedb');
var ICDB = {};
ICDB.chats = new Datastore({ filename: 'users.db', autoload: true});

**Comment by louischatriot** [comment]
Please show code with expected behaviour vs actual behaviour; code above is insufficient to help.

**Comment by hiteshkanani** [comment]
When i build exe file than after remove all saved records.

**Comment by hiteshkanani** [comment]
i wan't to just save all records

**Comment by hiteshkanani** [comment]
don't delete automatic records.

**Comment by hiteshkanani** [comment]
![image 1](https://user-images.githubusercontent.com/8766130/38092359-b30bb17e-3385-11e8-9b29-41c39cee8c96.png)
check image

**Comment by hiteshkanani** [comment]
Here is my step

1 Create Desktop App and Make Exe file
2 Open Desktop App By clicking on exe and save some records.
3 close this Desktop app
4 Again Open Desktop App By clicking on exe.
5 My saved record removed.
