### ISSUE TITLE
return only specific fields from db.find?

### ISSUE THREAD

**Issue by MaxYari** [louischatriot/nedb#559]
Hello there, I use nedb in electron to store some financial history data, each currency pair is a separate document and inside this document there's an array of at least 10k history entries. 
One of the features that I want to implement is an ability to fetch a list of available currency pairs. I would imagine that if i'll just fetch full docs with full history data - that will be pretty slow. So I was thinking that ability to actually return list of those docs without array fields will help it. Unfortunately I was unable to find in documentation something that will allow me to select (or deselect) specific return fields. Any way to do that?
Or maybe any general advise how I can optimise this data for such use case of fetching both list without arrays and single docs with arrays?
I was thinking about making duplicate entries, one for each use case, but would prefer to avoid it since it's a bit of a pain to keep it all in sync.

**Comment by JamesMGreene** [comment]
Explicitly defining which fields to either include or exclude is called "projection":

https://github.com/louischatriot/nedb#projections

**Comment by MaxYari** [comment]
Aww, that's great, thanks! :)
