### ISSUE TITLE
Can NeDB communicate with a remote server?

### ISSUE THREAD

**Issue by LoganDark** [louischatriot/nedb#560]
For example, one server would run the database, and there would be multiple other servers operating on the same database. Is that possible?

**Comment by JamesMGreene** [comment]
There is no existing connectivity in place to communicate off the machine/browser. If you're looking for that, I would suggest looking into MongoDB or maybe PouchDB.

**Comment by LoganDark** [comment]
When the entire reason I wanted to try NeDB is because of features I couldn't find in MongoDB or PouchDB, that is disappointing.

**Comment by JamesMGreene** [comment]
What compelling features does NeDB offer that the others do not?

**Comment by LoganDark** [comment]
Object-oriented NoSQL, I guess. I haven't researched NeDB too much because I've already moved onto creating my own database, but it's what I found at first.

I can let you know when it becomes open source, if you want!
