### ISSUE TITLE
Uncaught Error: EPERM: operation not permitted, rename

### ISSUE THREAD

**Issue by my07ke** [louischatriot/nedb#561]
Uncaught Error: EPERM: operation not permitted, rename 'D:\XXX\changeLog~' -> 'D:\XXX\db\changeLog'

![image](https://user-images.githubusercontent.com/17754548/41454431-f3ede794-70ab-11e8-9513-ceb9fb21e6cb.png)

![image](https://user-images.githubusercontent.com/17754548/41454665-d2777d5e-70ac-11e8-88d4-367a6152c146.png)

![image](https://user-images.githubusercontent.com/17754548/41454485-1c699722-70ac-11e8-876f-08cf2bda2468.png)

I often refresh the page a few times when it will happen。

**Comment by louischatriot** [comment]
Hello,

Can you please send a minimal code snippet that reproduces the issue? This looks very much like an issue with your system (you're on Windows is that correct?) but would love to check.

**Comment by my07ke** [comment]
Ok, at night I will extract some of the code and send it out。

**Comment by my07ke** [comment]
I found the reason is that "Synology" file synchronization problem。

After the program was shut down, there were no errors after tens of thousands of tests. This problem occurs when you open the test hundreds of times.
![image](https://user-images.githubusercontent.com/17754548/41479610-56276cf8-70fe-11e8-92a4-4b79e0074e7f.png)
