### ISSUE TITLE
Can't resolve 'path'

### ISSUE THREAD

**Issue by mluis** [louischatriot/nedb#563]
After running a `npm install nedb && npm run start` I'm getting:

```
ERROR in ./node_modules/nedb/lib/persistence.js
Module not found: Error: Can't resolve 'path' in '......./node_modules/nedb/lib'
```

edit:
node v10.4.1
npm 6.1.0

**Comment by marcelvoss95** [comment]
Try Adding the following to your package json dependencies


`
  "path": "^0.12.7",
`

Dependency seems to be missing in the project package.json
