### ISSUE TITLE
Compression with zlib

### ISSUE THREAD

**Issue by epneya** [louischatriot/nedb#568]
I'm trying to create an encrypted and as well compressed database using NeDB. The Encryption seems to work fine, but however the compression isn't working. NeDB throws an error saying the `afterSerialisation` and `beforeDeserialisation` are not the reverse of each other.

`Error: beforeDeserialization is not the reverse of afterSerialization, cautiously refusing to start NeDB to prevent dataloss`

I'm not sure, which structure the two functions have to be in and couldn't find any documentation for them. Not sure whether this is the right place to ask as well, but maybe you've got an idea, how to fix this. This is my code.

`afterSerialization: (data) => {`
  `try {`
    `let cipher  = crypto.createCipher(encryption.algorithm, encryption.key);`
    `data = cipher.update(JSON.stringify(data), 'utf8', 'hex') + cipher.final('hex');`
    `data = zlib.gzipSync(data);`
    `return data;`
  `} catch(err) {`
    `console.log(`ERROR: ${err}`);`
  `}`
`},`
`beforeDeserialization: (data) => {`
  `try {`
    `let decipher = crypto.createDecipher(encryption.algorithm, encryption.key);`
    `data = zlib.unzipSync(data);`
    `data = decipher.update(data, 'hex', 'utf8') + decipher.final('utf8');`
    `return JSON.parse(data);`
  `} catch(err) {`
    `console.log(`ERROR: ${err}`);`
  `}`
`}`

**Comment by epneya** [comment]
I guess, I now got a better understanding of what `afterSerialization` and `beforeDeserialization` demand and i think it wasn't really an issue with NeDB, but rather with the types, `zlib` and `Cipher` are using.

**Comment by acjay** [comment]
Out of curiosity, what did you end up with?

**Comment by arslanmughal5566** [comment]
Facing same issue while encrypting :( @epneya what was your solution ?
