### ISSUE TITLE
I have a few questions...

### ISSUE THREAD

**Issue by PassTheMayo** [louischatriot/nedb#574]
Hello, guys. I'm recently looking to switch from RethinkDB to NeDB for my website. It looks promising so far, but I still have some questions.

1. If I split my website up into multiple processes and each process shared the same database file, will the database on each process update when one changes the file?
2. Is it possible to use in-method ways of selecting data from the current document? (Example: `db.update((row) => ({ number: row.number + 1 }))` (takes every document and adds one to the `number` property))
3. Could this database stand up to heavy DOS attacks? (Essentially just lots of queries on db-heavy queries)

I hope you guys can help. Thanks!

**Comment by louischatriot** [comment]
Hello @PassTheMayo this seems like a clear case of "you should not use NeDB" :). NeDB is designed for self-contained, single process applications (usually either local or at least used by not too many people). If you're thinking about multiple processes and query throughput you want to use a full fledged database.
