### ISSUE TITLE
Inserting object as your _id fails with unexpected results

### ISSUE THREAD

**Issue by kryztoval** [louischatriot/nedb#576]
Sometimes it will remove the lines, or ignore them, or silently fail when processing

It seems this uses the _id in multiple ways, so saving a compound id as a unique key so you can't repeat a pair of values will break your storage and destroy all your data.

**Comment by JamesMGreene** [comment]
NeDB's `_id` fields are intended to be simple string values, though, as far as I can tell from the code, you could technically use any primitive type that supports `===`/`!==` comparisons.

It definitely does not support complex/compound objects for `_id` values.

**Comment by kryztoval** [comment]
Yes, That is what i am saying, if you use the _id with a compound it will match the first part but not the second, etc.
I could move around it using a JSON.stringify and JSON.parse on the _id and use the resulting string as the _id.

:D

**Comment by JamesMGreene** [comment]
> I could move around it using a JSON.stringify and JSON.parse on the _id and use the resulting string as the _id.

You could, though please keep in mind that `JSON.stringify` serialization order of properties in an object is not guaranteed to be stable natively, i.e. you _could_ end up with `'{"a":"apple","b":"bar"}'` one time and `'{"b":"bar","a":"apple"}'` the next. You would want to use a deterministic module for stringifying like [`fast-json-stable-stringify`](https://www.npmjs.com/package/fast-json-stable-stringify) or [`fast-safe-stringify`](https://www.npmjs.com/package/fast-safe-stringify), for example.

**Comment by kryztoval** [comment]
Yeah, you are right, Also I could just use a string formed with the parameters i want and do my own serialization, this does mean that i can't insert the object onto mongo withoth processing to convert the _id into a compound id, but it does solve the problem. Thank you!
