### ISSUE TITLE
decrement value on update

### ISSUE THREAD

**Issue by digimbyte** [louischatriot/nedb#590]
Hey, I am not too familiar with your structure or confident to do a pull request.
but when going over your update documentation, I noticed a way to increment a value but no way to decrement?

I was interested in using the database to track persistent life spans of objects, and when life hits 0, it would be removed.
as far as I know, it's not supported out of the box

**Comment by digimbyte** [comment]
didn't realize I could feed it a negative number

**Comment by J053Fabi0** [comment]
This could be a good example in the documentation.
