### ISSUE TITLE
QUESTION: I solved iterating an array with objects, but is there a better way?

### ISSUE THREAD

**Issue by fexell** [louischatriot/nedb#608]
So, I've been struggling with this part of the code for many hours today. I finally got it to work, but I'm wondering if I migh be overlooking everything and not realizing the "correct," or the more "prettier" way to do it? Here is the code:

DB object:
`{"name":"Test","todos":[{"id":"oi409u","title":"Test","desc":"Testing with todos...","isDone":false},{"id":"oi410e","title":"Test","desc":"Testing with todos...","isDone":false}],"_id":"Nc1euxGwLw8ZM7cw","createdAt":{"$$date":1566586466202},"updatedAt":{"$$date":1566589221418}}
`

Solution to change the "isDone" value:
```
toggle: function({ commit, state }, id) {
// id returns a todo-items "id."
let key
let todo = state.project.todos.filter( el => el.id === id )[ 0 ]

for( key in state.project.todos )
 if( todo === state.project.todos[ key ] )
  Vue._db.update({ "todos": todo }, { $set: { [`todos.${ key }.isDone`]: !todo.isDone } }, function() {

                    commit("TOGGLE", id)

  })

}
```

**Comment by fexell** [comment]
To be honest, it would be awesome if something like this `db.update({ "todos": todo }...` would actually return whatever it finds, store it as the context, instead of the entire doc it belongs to.

**Comment by chmac** [comment]
The readme says:

> IMPORTANT NOTE: Please don't submit issues for questions regarding your code. Only actual bugs or feature requests will be answered, all others will be closed without comment. Also, please follow the bug reporting guidelines and check the change log before submitting an already fixed bug :)

Please close your issue as the author does not answer questions here. You might try stackoverflow.

**Comment by fexell** [comment]
Closing this issue.
