### ISSUE TITLE
Question - Update/Insert Document

### ISSUE THREAD

**Issue by VimHax** [louischatriot/nedb#613]
I want to make it so a document is inserted if a document with the given ID doesn't exist, otherwise update the document. I want to know whether or not a built in function already does this. I know you can do this with a simple db.findOne & based on that db.insert or db.update but it would be a nice feature if it already doesn't exist! (Maybe it could be db.save)

```js
db.findOne({ _id: id }, (err, doc) => {
	if (err) { return reject(err); }
	if (doc) {
		db.update({ _id: id }, { data }, (err, newDoc) => {
			if (err) { return reject(err); }
			resolve(newDoc);
		});
	} else {
		db.insert({ _id: id, data }, (err, newDoc) => {
			if (err) { return reject(err); }
			resolve(newDoc);
		});
	}
});
```

**Comment by farayolaj** [comment]
If I understand your question well, you are asking for a way to update a document if it exists; insert it, if it doesn't.
You can set the `options.upsert` parameter to true. More about it in the [README.md] (https://github.com/louischatriot/nedb#updating-documents) file

**Comment by chmac** [comment]
The readme says:

> IMPORTANT NOTE: Please don't submit issues for questions regarding your code. Only actual bugs or feature requests will be answered, all others will be closed without comment. Also, please follow the bug reporting guidelines and check the change log before submitting an already fixed bug :)

Please close your issue as the author does not answer questions here. You might try stackoverflow.
