### ISSUE TITLE
Question about Retrieving Data after performing insert/update

### ISSUE THREAD

**Issue by nasyarobby** [louischatriot/nedb#614]
I have been using this library for a couple days, and so far I like it.
However I had an issue where everytime I insert/update a document, and then execute find(), the data does not include the latest data, unless I call loadDatabase().
Is it by design or I am missing something here?

**Comment by chmac** [comment]
The readme says:

> IMPORTANT NOTE: Please don't submit issues for questions regarding your code. Only actual bugs or feature requests will be answered, all others will be closed without comment. Also, please follow the bug reporting guidelines and check the change log before submitting an already fixed bug :)

Please close your issue as the author does not answer questions here. You might try stackoverflow.
