### ISSUE TITLE
Synchronous finds?

### ISSUE THREAD

**Issue by Jonovono** [louischatriot/nedb#91]
Is there a way to do finds that are synchronous or not?

**Comment by NathanHawks** [comment]
Uh-huh. *uninstalls, installs literally anything else* Oh look, synchronous finds.

**Comment by NathanHawks** [comment]
That's funny because literally every MySQL DBO I've ever used has featured it. And since Javascript doesn't offer a sleep function I literally don't even know how I'm supposed to make my app wait for your lib to READ FROM MEMORY long enough to avoid a race condition. W. T. F.
