### ISSUE TITLE
Dataloss possible when system crashes during loadDatabase

### ISSUE THREAD

**Issue by szwacz** [louischatriot/nedb#92]
Hello @louischatriot 

`loadDatabase` while running is rewriting the whole database file. This is quite fragile moment. If the system crashes at this time, data will be lost.

I don't know how probable is this issue, but I have run some dummy test...

``` javascript
var db = new Datastore({ filename: 'test.db' }); // file was 13MB

db.loadDatabase();

setTimeout(function () {
    process.exit(1);
}, 50);
```

...and data indeed was lost.

Possible fix would be ofcourse something like:
For file `test.db`
1. Change file name to `test.db.bac`
2. Do `loadDatabase` and save `test.db`
3. Remove `test.db.bac`
And while loading data first time we have to look first for `test.db.bac`

What do you think? Is it a real problem or too edge case to bother? Heh, life taught me there is no such thing like too edge case ;)

**Comment by louischatriot** [comment]
This implementation was in fact not correct and prone to dataloss in case of OS (not process) crash, if kernel buffer cache was not flushed to disk.

The new implementation is very much inspired from Redis AOF persistence, see this very interesting article by antirez: http://oldblog.antirez.com/post/redis-persistence-demystified.html

Implementation here if you want to look at it: https://github.com/louischatriot/nedb/blob/master/lib/storage.js

You'll notice it doesn't need two temp files to ensure data integrity, but hwat it does need and were not present are fsync calls after data change.
