### ISSUE TITLE
Compound indexes

### ISSUE THREAD

**Issue by Ivshti** [louischatriot/nedb#93]
It would help if ensureIndex could create compound indexes. Compound indexes will introduce huge optimizations for large collections if the queries work with several keys. And considering we have single-key indexes, compound indexes should not be hard to implement.

**Comment by Rajas-Git** [comment]
Does the compound index functionality works like MongoDB? 

> https://docs.mongodb.com/v3.0/tutorial/create-a-unique-index/#unique-compound-index
> `db.collection.createIndex( { a: 1, b: 1 }, { unique: true } )`
> These indexes **enforce uniqueness for the combination of index keys and not for either key individually.**

I tried the following:

```
db.ensureIndex({ fieldName :['first','second'], unique: true }, function(err) {
  if( err !== null ) console.error('ERROR in ensureIndex: '+err)  ;
});
```

But NeDB errors out if I try to do:

```
db.insert({first: 'A', second:'Z', function(err) {.....}); //inserts successfully.
db.insert({first: 'A', second:'Y', function(err) {.....}); //errors out. Can't insert key undefined, it violates the unique constraint
```
